public inherited sharing class KoopAPI_DluznikIndividualniItem {
    @AuraEnabled
    public String CISLO_SMLOUVY;
    @AuraEnabled
    public String CISLO_NAVRHU;
    @AuraEnabled
    public String KOD_PRODUKTU;
    @AuraEnabled
    public String VERZE_PRODUKTU;
    @AuraEnabled
    public String STAV_SMLOUVY;
    @AuraEnabled
    public String ZPUSOB_PLATBY;
    @AuraEnabled
    public String MESICU_DLUH;
    @AuraEnabled
    public Decimal SPLATKA;
    @AuraEnabled
    public Decimal CASTECNA_UHRADA;
    @AuraEnabled
    public Decimal DLUH;
    @AuraEnabled
    public String RC_ICO;
    @AuraEnabled
    public String PRIJMENI;
    @AuraEnabled
    public String JMENO;
    @AuraEnabled
    public String TITUL;
    @AuraEnabled
    public String ULICE;
    @AuraEnabled
    public String CISLO_DOMOVNI;
    @AuraEnabled
    public String PSC;
    @AuraEnabled
    public String OBEC;
    @AuraEnabled
    public String TELEFON;
    @AuraEnabled
    public String UPOMINKA_DATUM;
    @AuraEnabled
    public String UPOMINKA_INFO;
    @AuraEnabled
    public Decimal UPOMINKA_CASTKA;
    @AuraEnabled
    public String VYMAHANI_INFO;
    @AuraEnabled
    public Decimal ODPIS;
    @AuraEnabled
    public Decimal UPOMINACI_POPLATEK;
    @AuraEnabled
    public Decimal PREPLATEK;
    @AuraEnabled
    public String MAX_DATUM_SPLATNOSTI;
    @AuraEnabled
    public Decimal PROVIZE;
}
