public inherited sharing class KoopAPI_KmenDetailItem {
    @AuraEnabled
    public String CISLO_NAVRHU;
    @AuraEnabled
    public String CISLO_SMLOUVY;
    @AuraEnabled
    public String FLOTILA;
    @AuraEnabled
    public String DATUM_SJEDNANI;
    @AuraEnabled
    public String DATUM_POCATKU;
    @AuraEnabled
    public String DATUM_KONCE;
    @AuraEnabled
    public String DATUM_AKCEPTACE;
    @AuraEnabled
    public String KOD_PRODUKTU;
    @AuraEnabled
    public String VERZE_PRODUKTU;
    @AuraEnabled
    public String STAV_SMLOUVY;
    @AuraEnabled
    public String ZPUSOB_PLATBY;
    @AuraEnabled
    public String SJEDNATEL;
    @AuraEnabled
    public String KOD_PROVIZE;
    @AuraEnabled
    public String DATUM_ZAPLACENO_DO;
    @AuraEnabled
    public Integer FREKVENCE_PLACENI;
    @AuraEnabled
    public Decimal KMENOVE_POJISTNE;
    @AuraEnabled
    public Decimal LHUTNI_POJISTNE;
    @AuraEnabled
    public Decimal SLEVA_PRI_PROC;
    @AuraEnabled
    public Decimal SLEVA_PRI_KC;
    @AuraEnabled
    public Integer DNY_DLUHU;
    @AuraEnabled
    public Decimal DLUH;
}
