public inherited sharing class KoopAPI_VozidloItem {
    @AuraEnabled
    public String ID_VOZIDLO;
    @AuraEnabled
    public String RZ;
    @AuraEnabled
    public String VIN;
    @AuraEnabled
    public String ZNACKA;
    @AuraEnabled
    public String CISLO_TP;
    @AuraEnabled
    public String PALIVO;
    @AuraEnabled
    public String OBJEM_MOTOR;
    @AuraEnabled
    public String VYROBA;
    @AuraEnabled
    public String SEDADLA;
    @AuraEnabled
    public String HMOTNOST;
    @AuraEnabled
    public String VYKON_MOTOR;
    @AuraEnabled
    public String KATEGORIE;
}
