public inherited sharing class KoopAPI_RizikoItem {
    @AuraEnabled
    public String CISLO_SMLOUVY;
    @AuraEnabled
    public Integer ID_RIZIKO;
    @AuraEnabled
    public String RIZIKO_POPIS;
    @AuraEnabled
    public String ID_VOZIDLO;
    @AuraEnabled
    public String ID_PREDMET;
    @AuraEnabled
    public String ID_OSOBA;
    @AuraEnabled
    public Decimal POJISTNA_CASTKA;
    @AuraEnabled
    public Decimal POJISTNE;
    @AuraEnabled
    public Decimal SU_CASTKA;
    @AuraEnabled
    public Decimal SU_PROC;
    @AuraEnabled
    public Decimal SU_MINIMUM;
    @AuraEnabled
    public Decimal SU_MAXIMUM;
}
