public inherited sharing class KoopAPI_KmenItem {
    @AuraEnabled
    public String CISLO_SMLOUVY;
    @AuraEnabled
    public String CISLO_NAVRHU;
    @AuraEnabled
    public String FLOTILA;
    @AuraEnabled
    public String DATUM_SJEDNANI;
    @AuraEnabled
    public String DATUM_POCATKU;
    @AuraEnabled
    public String DATUM_KONCE;
    @AuraEnabled
    public String DATUM_AKCEPTACE;
    @AuraEnabled
    public String KOD_PRODUKTU;
    @AuraEnabled
    public String VERZE_PRODUKTU;
    @AuraEnabled
    public String STAV_SMLOUVY;
    @AuraEnabled
    public String ZPUSOB_PLATBY;
    @AuraEnabled
    public String SJEDNATEL;
    @AuraEnabled
    public String PRIJMENI;
    @AuraEnabled
    public String JMENO;
    @AuraEnabled
    public String TELEFON;
    @AuraEnabled
    public String EMAIL;
    @AuraEnabled
    public String RC_ICO;
    @AuraEnabled
    public String TITUL;
    @AuraEnabled
    public String ULICE;
    @AuraEnabled
    public String CISLO_DOMOVNI;
    @AuraEnabled
    public String PSC;
    @AuraEnabled
    public String OBEC;
    @AuraEnabled
    public String KOD_PROVIZE;
    @AuraEnabled
    public String DATUM_ZAPLACENO_DO;
    @AuraEnabled
    public Decimal KMENOVE_POJISTNE;
    @AuraEnabled
    public Decimal LHUTNI_POJISTNE;
    @AuraEnabled
    public Decimal SLEVA_PRI_PROC;
    @AuraEnabled
    public Decimal SLEVA_PRI_KC;
    @AuraEnabled
    public Integer DNY_DLUHU;
    @AuraEnabled
    public Decimal DLUH;
    @AuraEnabled
    public Integer FREKVENCE_PLACENI;
    @AuraEnabled
    public String KOD_STORNO;
    @AuraEnabled
    public String DATUM_PROVEDENI_STORNA;
    @AuraEnabled
    public String DATUM_UCINNOSTI_STORNA;
}
