public inherited sharing class KoopAPI_OsobaItem {
    @AuraEnabled
    public String ID_OSOBA;
    @AuraEnabled
    public String PRIJMENI;
    @AuraEnabled
    public String JMENO;
    @AuraEnabled
    public String TELEFON;
    @AuraEnabled
    public String EMAIL;
    @AuraEnabled
    public String RC_ICO;
    @AuraEnabled
    public String TITUL;
    @AuraEnabled
    public String ULICE;
    @AuraEnabled
    public String CISLO_DOMOVNI;
    @AuraEnabled
    public String PSC;
    @AuraEnabled
    public String OBEC;
}
