public inherited sharing class KoopAPI_CekarnaStorenItem {
    @AuraEnabled
    public String CISLO_SMLOUVY;
    @AuraEnabled
    public String CISLO_NAVRHU;
    @AuraEnabled
    public String FLOTILA;
    @AuraEnabled
    public String KOD_PRODUKTU;
    @AuraEnabled
    public String RC_ICO;
    @AuraEnabled
    public String PRIJMENI;
    @AuraEnabled
    public String JMENO;
    @AuraEnabled
    public String TITUL;
    @AuraEnabled
    public String ULICE;
    @AuraEnabled
    public String CISLO_DOMOVNI;
    @AuraEnabled
    public String PSC;
    @AuraEnabled
    public String OBEC;
    @AuraEnabled
    public String TELEFON;
    @AuraEnabled
    public String DATUM_REGISTRACE;
    @AuraEnabled
    public String DATUM_PR_STORNO;
    @AuraEnabled
    public String DATUM_UCINNOSTI;
    @AuraEnabled
    public String KOD_STORNO;
    @AuraEnabled
    public String POPIS_STORNO;
    @AuraEnabled
    public String STAV_SMLOUVY;
    @AuraEnabled
    public Decimal DLUH;
}
