public class KoopAPI {
    public class ArrayOfDluznikIndividualniItem {
        public KoopAPI.DluznikIndividualniItem[] DluznikIndividualniItem;
        private String[] DluznikIndividualniItem_type_info = new String[]{'DluznikIndividualniItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikIndividualniItem'};
    }
    public class DluznikIndividualniData {
        public KoopAPI.DluznikTable_element DluznikTable;
        public KoopAPI.ArrayOfDluznikIndividualniItem DluznikList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] DluznikTable_type_info = new String[]{'DluznikTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DluznikList_type_info = new String[]{'DluznikList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikTable','DluznikList','StatusList','DataInfo','log'};
    }
    public class NovaSmlouvaRozsirenaResponse_element {
        public KoopAPI.NovaSmlouvaDataRozsirena NovaSmlouvaRozsirenaResult;
        private String[] NovaSmlouvaRozsirenaResult_type_info = new String[]{'NovaSmlouvaRozsirenaResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaRozsirenaResult'};
    }
    public class ArrayOfPojistneUdalostiItem {
        public KoopAPI.PojistneUdalostiItem[] PojistneUdalostiItem;
        private String[] PojistneUdalostiItem_type_info = new String[]{'PojistneUdalostiItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PojistneUdalostiItem'};
    }
    public class ArrayOfCiselnikRizikoItem {
        public KoopAPI.CiselnikRizikoItem[] CiselnikRizikoItem;
        private String[] CiselnikRizikoItem_type_info = new String[]{'CiselnikRizikoItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikRizikoItem'};
    }
    public class ProvizeTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOfCiselnikStornoItem {
        public KoopAPI.CiselnikStornoItem[] CiselnikStornoItem;
        private String[] CiselnikStornoItem_type_info = new String[]{'CiselnikStornoItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikStornoItem'};
    }
    public class ArrayOfKmenDetailItem {
        public KoopAPI.KmenDetailItem[] KmenDetailItem;
        private String[] KmenDetailItem_type_info = new String[]{'KmenDetailItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenDetailItem'};
    }
    public class ArrayOfVozidloItem {
        public KoopAPI.VozidloItem[] VozidloItem;
        private String[] VozidloItem_type_info = new String[]{'VozidloItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'VozidloItem'};
    }
    public class ArrayOfRizikoItem {
        public KoopAPI.RizikoItem[] RizikoItem;
        private String[] RizikoItem_type_info = new String[]{'RizikoItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'RizikoItem'};
    }
    public class CiselnikZpusobPlatbyItem {
        public String ZPUSOB_PLATBY;
        public String POPIS;
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ZPUSOB_PLATBY','POPIS'};
    }
    public class CekarnaStorenItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String FLOTILA;
        public String KOD_PRODUKTU;
        public String RC_ICO;
        public String PRIJMENI;
        public String JMENO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String DATUM_REGISTRACE;
        public String DATUM_PR_STORNO;
        public String DATUM_UCINNOSTI;
        public String KOD_STORNO;
        public String POPIS_STORNO;
        public String STAV_SMLOUVY;
        public Decimal DLUH;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_REGISTRACE_type_info = new String[]{'DATUM_REGISTRACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PR_STORNO_type_info = new String[]{'DATUM_PR_STORNO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UCINNOSTI_type_info = new String[]{'DATUM_UCINNOSTI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_STORNO_type_info = new String[]{'KOD_STORNO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_STORNO_type_info = new String[]{'POPIS_STORNO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','FLOTILA','KOD_PRODUKTU','RC_ICO','PRIJMENI','JMENO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','DATUM_REGISTRACE','DATUM_PR_STORNO','DATUM_UCINNOSTI','KOD_STORNO','POPIS_STORNO','STAV_SMLOUVY','DLUH'};
    }
    public class ArrayOfArrayOfString {
        public KoopAPI.ArrayOfString[] ArrayOfString;
        private String[] ArrayOfString_type_info = new String[]{'ArrayOfString','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ArrayOfString'};
    }
    public class ProvizeResponse_element {
        public KoopAPI.ProvizeData ProvizeResult;
        private String[] ProvizeResult_type_info = new String[]{'ProvizeResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ProvizeResult'};
    }
    public class ArrayOfDokumentItem {
        public KoopAPI.DokumentItem[] DokumentItem;
        private String[] DokumentItem_type_info = new String[]{'DokumentItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DokumentItem'};
    }
    public class CiselnikyResponse_element {
        public KoopAPI.CiselnikyData CiselnikyResult;
        private String[] CiselnikyResult_type_info = new String[]{'CiselnikyResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikyResult'};
    }
    public class StavSmlouvyData {
        public KoopAPI.StavSmlouvyTable_element StavSmlouvyTable;
        public KoopAPI.ArrayOfStavSmlouvyItem StavSmlouvyList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] StavSmlouvyTable_type_info = new String[]{'StavSmlouvyTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StavSmlouvyList_type_info = new String[]{'StavSmlouvyList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'StavSmlouvyTable','StavSmlouvyList','StatusList','DataInfo','log'};
    }
    public class PNDCekarnaTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class CiselnikRoleNaSmlouveItem {
        public String ROLE_KOD;
        public String POPIS;
        private String[] ROLE_KOD_type_info = new String[]{'ROLE_KOD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ROLE_KOD','POPIS'};
    }
    public class StavSmlouvy_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String cisloSmlouvy;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisloSmlouvy_type_info = new String[]{'cisloSmlouvy','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','cisloSmlouvy','IDpartner','list_x'};
    }
    public class SmlouvaPNDAkceptaceResponse_element {
        public KoopAPI.SmlouvaPNDDataAkceptace SmlouvaPNDAkceptaceResult;
        private String[] SmlouvaPNDAkceptaceResult_type_info = new String[]{'SmlouvaPNDAkceptaceResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SmlouvaPNDAkceptaceResult'};
    }
    public class ArrayOfDluznikItem {
        public KoopAPI.DluznikItem[] DluznikItem;
        private String[] DluznikItem_type_info = new String[]{'DluznikItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikItem'};
    }
    public class DluznikItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String CISLO_PREDPISU;
        public String KOD_PRODUKTU;
        public String FLOTILA;
        public String RC_ICO;
        public String PRIJMENI;
        public String JMENO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String PREDPIS_OD;
        public String PREDPIS_DO;
        public String DATUM_VYSTAVENI;
        public String DATUM_SPLATNOSTI;
        public String DATUM_UHRADY;
        public String DATUM_UPOMINKY;
        public String DATUM_ZAPLACENO_DO;
        public Decimal SPLATKA;
        public Decimal CASTECNA_UHRADA;
        public Decimal DLUH;
        public String STAV_SMLOUVY;
        public String ZPUSOB_PLATBY;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_PREDPISU_type_info = new String[]{'CISLO_PREDPISU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PREDPIS_OD_type_info = new String[]{'PREDPIS_OD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PREDPIS_DO_type_info = new String[]{'PREDPIS_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_VYSTAVENI_type_info = new String[]{'DATUM_VYSTAVENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SPLATNOSTI_type_info = new String[]{'DATUM_SPLATNOSTI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UHRADY_type_info = new String[]{'DATUM_UHRADY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UPOMINKY_type_info = new String[]{'DATUM_UPOMINKY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_ZAPLACENO_DO_type_info = new String[]{'DATUM_ZAPLACENO_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SPLATKA_type_info = new String[]{'SPLATKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] CASTECNA_UHRADA_type_info = new String[]{'CASTECNA_UHRADA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','CISLO_PREDPISU','KOD_PRODUKTU','FLOTILA','RC_ICO','PRIJMENI','JMENO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','PREDPIS_OD','PREDPIS_DO','DATUM_VYSTAVENI','DATUM_SPLATNOSTI','DATUM_UHRADY','DATUM_UPOMINKY','DATUM_ZAPLACENO_DO','SPLATKA','CASTECNA_UHRADA','DLUH','STAV_SMLOUVY','ZPUSOB_PLATBY'};
    }
    public class CiselnikStornoItem {
        public String KOD_STORNO;
        public String POPIS;
        private String[] KOD_STORNO_type_info = new String[]{'KOD_STORNO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KOD_STORNO','POPIS'};
    }
    public class SmlouvyZaObdobiResponse_element {
        public KoopAPI.SmlouvyZaObdobiData SmlouvyZaObdobiResult;
        private String[] SmlouvyZaObdobiResult_type_info = new String[]{'SmlouvyZaObdobiResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SmlouvyZaObdobiResult'};
    }
    public class KmenDetailItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String FLOTILA;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public String DATUM_KONCE;
        public String DATUM_AKCEPTACE;
        public String KOD_PRODUKTU;
        public String VERZE_PRODUKTU;
        public String STAV_SMLOUVY;
        public String ZPUSOB_PLATBY;
        public String SJEDNATEL;
        public String KOD_PROVIZE;
        public String DATUM_ZAPLACENO_DO;
        public Integer FREKVENCE_PLACENI;
        public Decimal KMENOVE_POJISTNE;
        public Decimal LHUTNI_POJISTNE;
        public Decimal SLEVA_PRI_PROC;
        public Decimal SLEVA_PRI_KC;
        public Integer DNY_DLUHU;
        public Decimal DLUH;
        public KoopAPI.ArrayOfRoleOsobaItem RoleOsobaList;
        public KoopAPI.ArrayOfOsobaItem OsobaList;
        public KoopAPI.ArrayOfVozidloItem VozidloList;
        public KoopAPI.ArrayOfMistoPojisteniItem MistoPojisteniList;
        public KoopAPI.ArrayOfRizikoItem RizikoList;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_KONCE_type_info = new String[]{'DATUM_KONCE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_AKCEPTACE_type_info = new String[]{'DATUM_AKCEPTACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VERZE_PRODUKTU_type_info = new String[]{'VERZE_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PROVIZE_type_info = new String[]{'KOD_PROVIZE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_ZAPLACENO_DO_type_info = new String[]{'DATUM_ZAPLACENO_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FREKVENCE_PLACENI_type_info = new String[]{'FREKVENCE_PLACENI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] KMENOVE_POJISTNE_type_info = new String[]{'KMENOVE_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SLEVA_PRI_PROC_type_info = new String[]{'SLEVA_PRI_PROC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SLEVA_PRI_KC_type_info = new String[]{'SLEVA_PRI_KC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DNY_DLUHU_type_info = new String[]{'DNY_DLUHU','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] RoleOsobaList_type_info = new String[]{'RoleOsobaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OsobaList_type_info = new String[]{'OsobaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VozidloList_type_info = new String[]{'VozidloList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MistoPojisteniList_type_info = new String[]{'MistoPojisteniList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RizikoList_type_info = new String[]{'RizikoList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','FLOTILA','DATUM_SJEDNANI','DATUM_POCATKU','DATUM_KONCE','DATUM_AKCEPTACE','KOD_PRODUKTU','VERZE_PRODUKTU','STAV_SMLOUVY','ZPUSOB_PLATBY','SJEDNATEL','KOD_PROVIZE','DATUM_ZAPLACENO_DO','FREKVENCE_PLACENI','KMENOVE_POJISTNE','LHUTNI_POJISTNE','SLEVA_PRI_PROC','SLEVA_PRI_KC','DNY_DLUHU','DLUH','RoleOsobaList','OsobaList','VozidloList','MistoPojisteniList','RizikoList'};
    }
    public class ArrayOfProvizeItem {
        public KoopAPI.ProvizeItem[] ProvizeItem;
        private String[] ProvizeItem_type_info = new String[]{'ProvizeItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ProvizeItem'};
    }
    public class ProvizeItem {
        public String UZAVERKA;
        public String CISLO_SMLOUVY;
        public String KOD_PRODUKTU;
        public String RC_ICO;
        public String JMENO;
        public String PRIJMENI;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String OBDOBI_OD;
        public String OBDOBI_DO;
        public String KOD_ZAKLADEN_PROVIZI;
        public String CISLO_NAVRHU;
        public String TYP_ODMENY;
        public String ZPUSOB_VYPLATY;
        public String FLOTILA;
        public String HIP;
        public String SJEDNATEL;
        public String KOD_PROVIZE;
        public Integer CISLO_PREDPISU;
        public Integer POCET_LET_SMLOUVY;
        public Integer PORADI_ROKU;
        public Integer PRIZNAK_PROVIZE;
        public Decimal ZAKLADNA_PROVIZE;
        public Decimal DELBA_NA_CINNOST;
        public Decimal KOEFICIENT_PROVIZE;
        public Decimal ZAKLADNA_KM;
        public Decimal KOEF_MNOZSTVI;
        public Decimal PROVIZE_VYPOCTENA;
        public Decimal ZAKLADNA_UC;
        public Decimal ZAKLADNA_ZAM;
        public Boolean RUCNI_PROVIZE_AN;
        public Boolean MAKLER_STRHAVA_PROVIZI_AN;
        private String[] UZAVERKA_type_info = new String[]{'UZAVERKA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBDOBI_OD_type_info = new String[]{'OBDOBI_OD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBDOBI_DO_type_info = new String[]{'OBDOBI_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_ZAKLADEN_PROVIZI_type_info = new String[]{'KOD_ZAKLADEN_PROVIZI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TYP_ODMENY_type_info = new String[]{'TYP_ODMENY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_VYPLATY_type_info = new String[]{'ZPUSOB_VYPLATY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] HIP_type_info = new String[]{'HIP','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PROVIZE_type_info = new String[]{'KOD_PROVIZE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_PREDPISU_type_info = new String[]{'CISLO_PREDPISU','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] POCET_LET_SMLOUVY_type_info = new String[]{'POCET_LET_SMLOUVY','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] PORADI_ROKU_type_info = new String[]{'PORADI_ROKU','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] PRIZNAK_PROVIZE_type_info = new String[]{'PRIZNAK_PROVIZE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ZAKLADNA_PROVIZE_type_info = new String[]{'ZAKLADNA_PROVIZE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DELBA_NA_CINNOST_type_info = new String[]{'DELBA_NA_CINNOST','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] KOEFICIENT_PROVIZE_type_info = new String[]{'KOEFICIENT_PROVIZE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ZAKLADNA_KM_type_info = new String[]{'ZAKLADNA_KM','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] KOEF_MNOZSTVI_type_info = new String[]{'KOEF_MNOZSTVI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] PROVIZE_VYPOCTENA_type_info = new String[]{'PROVIZE_VYPOCTENA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ZAKLADNA_UC_type_info = new String[]{'ZAKLADNA_UC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ZAKLADNA_ZAM_type_info = new String[]{'ZAKLADNA_ZAM','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] RUCNI_PROVIZE_AN_type_info = new String[]{'RUCNI_PROVIZE_AN','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] MAKLER_STRHAVA_PROVIZI_AN_type_info = new String[]{'MAKLER_STRHAVA_PROVIZI_AN','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UZAVERKA','CISLO_SMLOUVY','KOD_PRODUKTU','RC_ICO','JMENO','PRIJMENI','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','OBDOBI_OD','OBDOBI_DO','KOD_ZAKLADEN_PROVIZI','CISLO_NAVRHU','TYP_ODMENY','ZPUSOB_VYPLATY','FLOTILA','HIP','SJEDNATEL','KOD_PROVIZE','CISLO_PREDPISU','POCET_LET_SMLOUVY','PORADI_ROKU','PRIZNAK_PROVIZE','ZAKLADNA_PROVIZE','DELBA_NA_CINNOST','KOEFICIENT_PROVIZE','ZAKLADNA_KM','KOEF_MNOZSTVI','PROVIZE_VYPOCTENA','ZAKLADNA_UC','ZAKLADNA_ZAM','RUCNI_PROVIZE_AN','MAKLER_STRHAVA_PROVIZI_AN'};
    }
    public class UzivatelKnz_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String IDpartner;
        public Boolean vse;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] vse_type_info = new String[]{'vse','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','IDpartner','vse','list_x'};
    }
    public class StavSmlouvyTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class NIItem {
        public String ZISKATEL_KOD;
        public String KLIENT;
        public String CISLO_SMLOUVY;
        public String KOD_PRODUKTU;
        public String MOBIL;
        public String TELEFON;
        public String RC_ICO;
        public String DATUM_POCATKU;
        public String DATUM_TERMIN_NI;
        public String DATUM_VYTVORENI_NI;
        public String POZADAVEK_CISLO;
        public String DokumentNI_DATA;
        public String DokumentNI_JMENO;
        public String DokumentNI_MIMETYPE;
        private String[] ZISKATEL_KOD_type_info = new String[]{'ZISKATEL_KOD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KLIENT_type_info = new String[]{'KLIENT','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MOBIL_type_info = new String[]{'MOBIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_TERMIN_NI_type_info = new String[]{'DATUM_TERMIN_NI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_VYTVORENI_NI_type_info = new String[]{'DATUM_VYTVORENI_NI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POZADAVEK_CISLO_type_info = new String[]{'POZADAVEK_CISLO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DokumentNI_DATA_type_info = new String[]{'DokumentNI_DATA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DokumentNI_JMENO_type_info = new String[]{'DokumentNI_JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DokumentNI_MIMETYPE_type_info = new String[]{'DokumentNI_MIMETYPE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ZISKATEL_KOD','KLIENT','CISLO_SMLOUVY','KOD_PRODUKTU','MOBIL','TELEFON','RC_ICO','DATUM_POCATKU','DATUM_TERMIN_NI','DATUM_VYTVORENI_NI','POZADAVEK_CISLO','DokumentNI_DATA','DokumentNI_JMENO','DokumentNI_MIMETYPE'};
    }
    public class StatusDetail {
        public Boolean PrubehOK;
        public String Popis;
        private String[] PrubehOK_type_info = new String[]{'PrubehOK','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] Popis_type_info = new String[]{'Popis','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PrubehOK','Popis'};
    }
    public class CiselnikRizikoItem {
        public String ID_RIZIKO;
        public String POPIS;
        private String[] ID_RIZIKO_type_info = new String[]{'ID_RIZIKO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ID_RIZIKO','POPIS'};
    }
    public class PNDSmlouvaTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class CiselnikProduktItem {
        public String KOD_PP;
        public String POPIS;
        public String PLATNOST_OD;
        public String PLATNOST_DO;
        private String[] KOD_PP_type_info = new String[]{'KOD_PP','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PLATNOST_OD_type_info = new String[]{'PLATNOST_OD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PLATNOST_DO_type_info = new String[]{'PLATNOST_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KOD_PP','POPIS','PLATNOST_OD','PLATNOST_DO'};
    }
    public class InvesticeTipResponse_element {
        public KoopAPI.InvesticeData InvesticeTipResult;
        private String[] InvesticeTipResult_type_info = new String[]{'InvesticeTipResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'InvesticeTipResult'};
    }
    public class UkonceneResponse_element {
        public KoopAPI.UkonceneSmlouvyData UkonceneResult;
        private String[] UkonceneResult_type_info = new String[]{'UkonceneResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UkonceneResult'};
    }
    public class ArrayOfStatusDetail {
        public KoopAPI.StatusDetail[] StatusDetail;
        private String[] StatusDetail_type_info = new String[]{'StatusDetail','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'StatusDetail'};
    }
    public class NeinkasniIntervenceResponse_element {
        public KoopAPI.NeinkasniIntervenceData NeinkasniIntervenceResult;
        private String[] NeinkasniIntervenceResult_type_info = new String[]{'NeinkasniIntervenceResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NeinkasniIntervenceResult'};
    }
    public class CekarnaStorenTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOfRoleOsobaItem {
        public KoopAPI.RoleOsobaItem[] RoleOsobaItem;
        private String[] RoleOsobaItem_type_info = new String[]{'RoleOsobaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'RoleOsobaItem'};
    }
    public class DocumentsData {
        public KoopAPI.ArrayOfDokumentItem DokumentList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] DokumentList_type_info = new String[]{'DokumentList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DokumentList','StatusList','DataInfo','log'};
    }
    public class NeinkasniIntervence_element {
        public String IDpartner;
        public Integer DnyZpetne;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DnyZpetne_type_info = new String[]{'DnyZpetne','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','DnyZpetne'};
    }
    public class Novinky_element {
        public String IDpartner;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner'};
    }
    public class ArrayOfStavSmlouvyItem {
        public KoopAPI.StavSmlouvyItem[] StavSmlouvyItem;
        private String[] StavSmlouvyItem_type_info = new String[]{'StavSmlouvyItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'StavSmlouvyItem'};
    }
    public class UzivatelKnzData {
        public KoopAPI.UzivatelKnzTable_element UzivatelKnzTable;
        public KoopAPI.ArrayOfUzivatelKnzItem UzivatelKnzList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] UzivatelKnzTable_type_info = new String[]{'UzivatelKnzTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UzivatelKnzList_type_info = new String[]{'UzivatelKnzList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UzivatelKnzTable','UzivatelKnzList','StatusList','DataInfo','log'};
    }
    public class LogFile {
        public String FilePrefix;
        public String FilePath;
        public Integer FileSizeLimit;
        public Boolean MonthlyLog;
        public Boolean WeeklyLog;
        private String[] FilePrefix_type_info = new String[]{'FilePrefix','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FilePath_type_info = new String[]{'FilePath','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FileSizeLimit_type_info = new String[]{'FileSizeLimit','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] MonthlyLog_type_info = new String[]{'MonthlyLog','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] WeeklyLog_type_info = new String[]{'WeeklyLog','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'FilePrefix','FilePath','FileSizeLimit','MonthlyLog','WeeklyLog'};
    }
    public class OsobaItem {
        public String ID_OSOBA;
        public String PRIJMENI;
        public String JMENO;
        public String TELEFON;
        public String EMAIL;
        public String RC_ICO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        private String[] ID_OSOBA_type_info = new String[]{'ID_OSOBA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ID_OSOBA','PRIJMENI','JMENO','TELEFON','EMAIL','RC_ICO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC'};
    }
    public class SmlouvaPNDAkceptaceItem {
        public String CISLO_SMLOUVY;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public String DATUM_KONCE;
        public String DATUM_AKCEPTACE;
        public String KOD_PRODUKTU;
        public String PRIJMENI;
        public String JMENO;
        public String TELEFON;
        public String MOBIL;
        public String EMAIL;
        public String RC_ICO;
        public String ZPUSOB_PLATBY;
        public String CELE_JMENO;
        public String SJEDNATEL;
        public Decimal ROCNI;
        public Integer FREKVENCE_PLACENI;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_KONCE_type_info = new String[]{'DATUM_KONCE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_AKCEPTACE_type_info = new String[]{'DATUM_AKCEPTACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MOBIL_type_info = new String[]{'MOBIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CELE_JMENO_type_info = new String[]{'CELE_JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ROCNI_type_info = new String[]{'ROCNI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] FREKVENCE_PLACENI_type_info = new String[]{'FREKVENCE_PLACENI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','DATUM_SJEDNANI','DATUM_POCATKU','DATUM_KONCE','DATUM_AKCEPTACE','KOD_PRODUKTU','PRIJMENI','JMENO','TELEFON','MOBIL','EMAIL','RC_ICO','ZPUSOB_PLATBY','CELE_JMENO','SJEDNATEL','ROCNI','FREKVENCE_PLACENI'};
    }
    public class PNDCekarnaResponse_element {
        public KoopAPI.SmlouvaPNDCekarnaData PNDCekarnaResult;
        private String[] PNDCekarnaResult_type_info = new String[]{'PNDCekarnaResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDCekarnaResult'};
    }
    public class ArrayOfSmlouvaPNDCekarnaItem {
        public KoopAPI.SmlouvaPNDCekarnaItem[] SmlouvaPNDCekarnaItem;
        private String[] SmlouvaPNDCekarnaItem_type_info = new String[]{'SmlouvaPNDCekarnaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SmlouvaPNDCekarnaItem'};
    }
    public class ArrayOfCekarnaStorenItem {
        public KoopAPI.CekarnaStorenItem[] CekarnaStorenItem;
        private String[] CekarnaStorenItem_type_info = new String[]{'CekarnaStorenItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CekarnaStorenItem'};
    }
    public class PojistneUdalostiData {
        public KoopAPI.PojistneUdalostiTable_element PojistneUdalostiTable;
        public KoopAPI.ArrayOfPojistneUdalostiItem PojistneUdalostiList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] PojistneUdalostiTable_type_info = new String[]{'PojistneUdalostiTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PojistneUdalostiList_type_info = new String[]{'PojistneUdalostiList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PojistneUdalostiTable','PojistneUdalostiList','StatusList','DataInfo','log'};
    }
    public class SmlouvaPNDCekarnaData {
        public KoopAPI.PNDCekarnaTable_element PNDCekarnaTable;
        public KoopAPI.ArrayOfSmlouvaPNDCekarnaItem PNDCekarnaList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] PNDCekarnaTable_type_info = new String[]{'PNDCekarnaTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PNDCekarnaList_type_info = new String[]{'PNDCekarnaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDCekarnaTable','PNDCekarnaList','StatusList','DataInfo','log'};
    }
    public class Kmen_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String stavSmlouvy;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] stavSmlouvy_type_info = new String[]{'stavSmlouvy','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','stavSmlouvy','IDpartner','list_x'};
    }
    public class ArrayOfNovaSmlouvaVDPItem {
        public KoopAPI.NovaSmlouvaVDPItem[] NovaSmlouvaVDPItem;
        private String[] NovaSmlouvaVDPItem_type_info = new String[]{'NovaSmlouvaVDPItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaVDPItem'};
    }
    public class ArrayOfNovaSmlouvaRozsirenaItem {
        public KoopAPI.NovaSmlouvaRozsirenaItem[] NovaSmlouvaRozsirenaItem;
        private String[] NovaSmlouvaRozsirenaItem_type_info = new String[]{'NovaSmlouvaRozsirenaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaRozsirenaItem'};
    }
    public class BaseExtra {
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'StatusList','DataInfo','log'};
    }
    public class UkonceneSmlouvyData {
        public KoopAPI.UkonceneSmlouvyTable_element UkonceneSmlouvyTable;
        public KoopAPI.ArrayOfUkonceneSmlouvyItem UkonceneSmlouvyList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] UkonceneSmlouvyTable_type_info = new String[]{'UkonceneSmlouvyTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UkonceneSmlouvyList_type_info = new String[]{'UkonceneSmlouvyList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UkonceneSmlouvyTable','UkonceneSmlouvyList','StatusList','DataInfo','log'};
    }
    public class ArrayOfZiskatel {
        public KoopAPI.Ziskatel[] Ziskatel;
        private String[] Ziskatel_type_info = new String[]{'Ziskatel','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'Ziskatel'};
    }
    public class Ukoncene_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public Integer mesic;
        public Integer rok;
        public String typ;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] mesic_type_info = new String[]{'mesic','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] rok_type_info = new String[]{'rok','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] typ_type_info = new String[]{'typ','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','mesic','rok','typ','IDpartner','list_x'};
    }
    public class DluznikFlotilaData {
        public KoopAPI.DluznikTable_element DluznikTable;
        public KoopAPI.ArrayOfDluznikFlotilaItem DluznikList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] DluznikTable_type_info = new String[]{'DluznikTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DluznikList_type_info = new String[]{'DluznikList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikTable','DluznikList','StatusList','DataInfo','log'};
    }
    public class DluznikResponse_element {
        public KoopAPI.DluznikData DluznikResult;
        private String[] DluznikResult_type_info = new String[]{'DluznikResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikResult'};
    }
    public class InvesticeItem {
        public DateTime Datum_jednani;
        public String Klient_nazev;
        public String Klient_mobil;
        public String Klient_email;
        public String Zisk_kod;
        public String Zisk_nazev;
        public String Kontakt_zisk_kod;
        public String Kontakt_zisk_nazev;
        public String Potreba_info;
        private String[] Datum_jednani_type_info = new String[]{'Datum_jednani','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] Klient_nazev_type_info = new String[]{'Klient_nazev','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Klient_mobil_type_info = new String[]{'Klient_mobil','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Klient_email_type_info = new String[]{'Klient_email','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Zisk_kod_type_info = new String[]{'Zisk_kod','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Zisk_nazev_type_info = new String[]{'Zisk_nazev','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Kontakt_zisk_kod_type_info = new String[]{'Kontakt_zisk_kod','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Kontakt_zisk_nazev_type_info = new String[]{'Kontakt_zisk_nazev','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Potreba_info_type_info = new String[]{'Potreba_info','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'Datum_jednani','Klient_nazev','Klient_mobil','Klient_email','Zisk_kod','Zisk_nazev','Kontakt_zisk_kod','Kontakt_zisk_nazev','Potreba_info'};
    }
    public class Ziskatel {
        public String CisloZiskatele;
        private String[] CisloZiskatele_type_info = new String[]{'CisloZiskatele','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CisloZiskatele'};
    }
    public class ArrayOfCiselnikRoleNaSmlouveItem {
        public KoopAPI.CiselnikRoleNaSmlouveItem[] CiselnikRoleNaSmlouveItem;
        private String[] CiselnikRoleNaSmlouveItem_type_info = new String[]{'CiselnikRoleNaSmlouveItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikRoleNaSmlouveItem'};
    }
    public class ArrayOfCiselnikStavSmlouvyItem {
        public KoopAPI.CiselnikStavSmlouvyItem[] CiselnikStavSmlouvyItem;
        private String[] CiselnikStavSmlouvyItem_type_info = new String[]{'CiselnikStavSmlouvyItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikStavSmlouvyItem'};
    }
    public class NovaSmlouvaDataRozsirena {
        public KoopAPI.NovaSmlouvaTable_element NovaSmlouvaTable;
        public KoopAPI.ArrayOfNovaSmlouvaRozsirenaItem NovaSmlouvaList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] NovaSmlouvaTable_type_info = new String[]{'NovaSmlouvaTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] NovaSmlouvaList_type_info = new String[]{'NovaSmlouvaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaTable','NovaSmlouvaList','StatusList','DataInfo','log'};
    }
    public class NeinkasniIntervenceData {
        public KoopAPI.ArrayOfNIItem NIList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] NIList_type_info = new String[]{'NIList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NIList','StatusList','DataInfo','log'};
    }
    public class ArrayOfOsobaItem {
        public KoopAPI.OsobaItem[] OsobaItem;
        private String[] OsobaItem_type_info = new String[]{'OsobaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'OsobaItem'};
    }
    public class InvesticeTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class Pojistneudalosti_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String datumVznikOd;
        public String datumHlaseniOd;
        public String cisloSmlouvy;
        public String cisloNavrhu;
        public String cisloUdalosti;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] datumVznikOd_type_info = new String[]{'datumVznikOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] datumHlaseniOd_type_info = new String[]{'datumHlaseniOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisloSmlouvy_type_info = new String[]{'cisloSmlouvy','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisloNavrhu_type_info = new String[]{'cisloNavrhu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisloUdalosti_type_info = new String[]{'cisloUdalosti','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','datumVznikOd','datumHlaseniOd','cisloSmlouvy','cisloNavrhu','cisloUdalosti','IDpartner','list_x'};
    }
    public class KmenData {
        public KoopAPI.KmenTable_element KmenTable;
        public KoopAPI.ArrayOfKmenItem KmenList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] KmenTable_type_info = new String[]{'KmenTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KmenList_type_info = new String[]{'KmenList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenTable','KmenList','StatusList','DataInfo','log'};
    }
    public class ArrayOfMistoPojisteniItem {
        public KoopAPI.MistoPojisteniItem[] MistoPojisteniItem;
        private String[] MistoPojisteniItem_type_info = new String[]{'MistoPojisteniItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'MistoPojisteniItem'};
    }
    public class DluznikFlotilaResponse_element {
        public KoopAPI.DluznikFlotilaData DluznikFlotilaResult;
        private String[] DluznikFlotilaResult_type_info = new String[]{'DluznikFlotilaResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikFlotilaResult'};
    }
    public class ArrayOfCiselnikZpusobPlatbyItem {
        public KoopAPI.CiselnikZpusobPlatbyItem[] CiselnikZpusobPlatbyItem;
        private String[] CiselnikZpusobPlatbyItem_type_info = new String[]{'CiselnikZpusobPlatbyItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikZpusobPlatbyItem'};
    }
    public class Ciselniky_element {
        public String IDpartner;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner'};
    }
    public class PNDNestalecData {
        public KoopAPI.PNDNestalecTable_element PNDNestalecTable;
        public KoopAPI.ArrayOfPNDNestalecItem PNDNestalecList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] PNDNestalecTable_type_info = new String[]{'PNDNestalecTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PNDNestalecList_type_info = new String[]{'PNDNestalecList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDNestalecTable','PNDNestalecList','StatusList','DataInfo','log'};
    }
    public class UzivatelKnzTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class UkonceneSmlouvyTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOfNIItem {
        public KoopAPI.NIItem[] NIItem;
        private String[] NIItem_type_info = new String[]{'NIItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NIItem'};
    }
    public class DluznikData {
        public KoopAPI.DluznikTable_element DluznikTable;
        public KoopAPI.ArrayOfDluznikItem DluznikList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] DluznikTable_type_info = new String[]{'DluznikTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DluznikList_type_info = new String[]{'DluznikList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikTable','DluznikList','StatusList','DataInfo','log'};
    }
    public class KmenDetailData {
        public KoopAPI.ArrayOfKmenDetailItem KmenDetailList;
        public KoopAPI.ArrayOfRoleOsobaItem RoleOsobaList;
        public KoopAPI.ArrayOfOsobaItem OsobaList;
        public KoopAPI.ArrayOfVozidloItem VozidloList;
        public KoopAPI.ArrayOfMistoPojisteniItem MistoPojisteniList;
        public KoopAPI.ArrayOfRizikoItem RizikoList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] KmenDetailList_type_info = new String[]{'KmenDetailList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RoleOsobaList_type_info = new String[]{'RoleOsobaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OsobaList_type_info = new String[]{'OsobaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VozidloList_type_info = new String[]{'VozidloList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MistoPojisteniList_type_info = new String[]{'MistoPojisteniList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RizikoList_type_info = new String[]{'RizikoList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenDetailList','RoleOsobaList','OsobaList','VozidloList','MistoPojisteniList','RizikoList','StatusList','DataInfo','log'};
    }
    public class ArrayOfUzivatelKnzItem {
        public KoopAPI.UzivatelKnzItem[] UzivatelKnzItem;
        private String[] UzivatelKnzItem_type_info = new String[]{'UzivatelKnzItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UzivatelKnzItem'};
    }
    public class SouborItem {
        public String Data;
        public String JmenoSouboru;
        public String TypSouboru;
        private String[] Data_type_info = new String[]{'Data','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JmenoSouboru_type_info = new String[]{'JmenoSouboru','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TypSouboru_type_info = new String[]{'TypSouboru','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'Data','JmenoSouboru','TypSouboru'};
    }
    public class ProvizeData {
        public KoopAPI.ProvizeTable_element ProvizeTable;
        public KoopAPI.ArrayOfProvizeItem ProvizeList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] ProvizeTable_type_info = new String[]{'ProvizeTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ProvizeList_type_info = new String[]{'ProvizeList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ProvizeTable','ProvizeList','StatusList','DataInfo','log'};
    }
    public class RoleOsobaItem {
        public String CISLO_SMLOUVY;
        public String ID_OSOBA;
        public String ROLE_KOD;
        public String ROLE_POPIS;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_OSOBA_type_info = new String[]{'ID_OSOBA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ROLE_KOD_type_info = new String[]{'ROLE_KOD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ROLE_POPIS_type_info = new String[]{'ROLE_POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','ID_OSOBA','ROLE_KOD','ROLE_POPIS'};
    }
    public class NovaSmlouvaVDP_element {
        public String IDpartner;
        public String kodZi;
        public String DatumOd;
        public Boolean list_x;
        public String IDdotazu;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] kodZi_type_info = new String[]{'kodZi','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumOd_type_info = new String[]{'DatumOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDdotazu_type_info = new String[]{'IDdotazu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','kodZi','DatumOd','list_x','IDdotazu'};
    }
    public class CiselnikyData {
        public KoopAPI.ArrayOfCiselnikProduktItem CiselnikProduktList;
        public KoopAPI.ArrayOfCiselnikStavSmlouvyItem CiselnikStavSmlouvyList;
        public KoopAPI.ArrayOfCiselnikFrekvencePlaceniItem CiselnikFrekvencePlaceniList;
        public KoopAPI.ArrayOfCiselnikZpusobPlatbyItem CiselnikZpusobPlatbyList;
        public KoopAPI.ArrayOfCiselnikRizikoItem CiselnikRizikoList;
        public KoopAPI.ArrayOfCiselnikRoleNaSmlouveItem CiselnikRoleNaSmlouveList;
        public KoopAPI.ArrayOfCiselnikStornoItem CiselnikStornoList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] CiselnikProduktList_type_info = new String[]{'CiselnikProduktList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikStavSmlouvyList_type_info = new String[]{'CiselnikStavSmlouvyList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikFrekvencePlaceniList_type_info = new String[]{'CiselnikFrekvencePlaceniList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikZpusobPlatbyList_type_info = new String[]{'CiselnikZpusobPlatbyList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikRizikoList_type_info = new String[]{'CiselnikRizikoList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikRoleNaSmlouveList_type_info = new String[]{'CiselnikRoleNaSmlouveList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CiselnikStornoList_type_info = new String[]{'CiselnikStornoList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikProduktList','CiselnikStavSmlouvyList','CiselnikFrekvencePlaceniList','CiselnikZpusobPlatbyList','CiselnikRizikoList','CiselnikRoleNaSmlouveList','CiselnikStornoList','StatusList','DataInfo','log'};
    }
    public class DluznikTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class ArrayOfNovinkaItem {
        public KoopAPI.NovinkaItem[] NovinkaItem;
        private String[] NovinkaItem_type_info = new String[]{'NovinkaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovinkaItem'};
    }
    public class KmenDetail_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String cisloSmlouvy;
        public String IDpartner;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisloSmlouvy_type_info = new String[]{'cisloSmlouvy','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','cisloSmlouvy','IDpartner'};
    }
    public class ArrayOfPNDNestalecItem {
        public KoopAPI.PNDNestalecItem[] PNDNestalecItem;
        private String[] PNDNestalecItem_type_info = new String[]{'PNDNestalecItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDNestalecItem'};
    }
    public class PNDNestalecItem {
        public String VS_PLATBY;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public Decimal LHUTNI_POJISTNE;
        public Decimal CASTKA_PLATBY;
        public String DATUM_PLATBY;
        private String[] VS_PLATBY_type_info = new String[]{'VS_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] CASTKA_PLATBY_type_info = new String[]{'CASTKA_PLATBY','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DATUM_PLATBY_type_info = new String[]{'DATUM_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'VS_PLATBY','DATUM_SJEDNANI','DATUM_POCATKU','LHUTNI_POJISTNE','CASTKA_PLATBY','DATUM_PLATBY'};
    }
    public class DokumentySmlouvyResponse_element {
        public KoopAPI.DocumentsData DokumentySmlouvyResult;
        private String[] DokumentySmlouvyResult_type_info = new String[]{'DokumentySmlouvyResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DokumentySmlouvyResult'};
    }
    public class SmlouvaPNDDataAkceptace {
        public KoopAPI.PNDSmlouvaTable_element PNDSmlouvaTable;
        public KoopAPI.ArrayOfSmlouvaPNDAkceptaceItem PNDSmlouvaList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] PNDSmlouvaTable_type_info = new String[]{'PNDSmlouvaTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PNDSmlouvaList_type_info = new String[]{'PNDSmlouvaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDSmlouvaTable','PNDSmlouvaList','StatusList','DataInfo','log'};
    }
    public class CiselnikFrekvencePlaceniItem {
        public String FREKVENCE_PLACENI;
        public String POPIS;
        private String[] FREKVENCE_PLACENI_type_info = new String[]{'FREKVENCE_PLACENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'FREKVENCE_PLACENI','POPIS'};
    }
    public class PNDCekarna_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String stavSmlouvy;
        public String cisloSmlouvy;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] stavSmlouvy_type_info = new String[]{'stavSmlouvy','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] cisloSmlouvy_type_info = new String[]{'cisloSmlouvy','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','stavSmlouvy','cisloSmlouvy','IDpartner','list_x'};
    }
    public class NovaSmlouvaVDPItem {
        public KoopAPI.ArrayOfDokumentItem DokumentList;
        public String CISLO_SMLOUVY;
        public String KOD_PRODUKTU;
        public String POJISTNIK_RC_IC;
        public String POJISTNIK_NAZEV;
        public String POJISTNIK_EMAIL;
        public String SJEDNATEL;
        public String DATUM_VLOZENI;
        public Boolean VDP;
        private String[] DokumentList_type_info = new String[]{'DokumentList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POJISTNIK_RC_IC_type_info = new String[]{'POJISTNIK_RC_IC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POJISTNIK_NAZEV_type_info = new String[]{'POJISTNIK_NAZEV','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POJISTNIK_EMAIL_type_info = new String[]{'POJISTNIK_EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_VLOZENI_type_info = new String[]{'DATUM_VLOZENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VDP_type_info = new String[]{'VDP','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DokumentList','CISLO_SMLOUVY','KOD_PRODUKTU','POJISTNIK_RC_IC','POJISTNIK_NAZEV','POJISTNIK_EMAIL','SJEDNATEL','DATUM_VLOZENI','VDP'};
    }
    public class PojistneUdalostiTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class KmenDetailResponse_element {
        public KoopAPI.KmenDetailData KmenDetailResult;
        private String[] KmenDetailResult_type_info = new String[]{'KmenDetailResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenDetailResult'};
    }
    public class PNDNestalecResponse_element {
        public KoopAPI.PNDNestalecData PNDNestalecResult;
        private String[] PNDNestalecResult_type_info = new String[]{'PNDNestalecResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PNDNestalecResult'};
    }
    public class ArrayOfDluznikFlotilaItem {
        public KoopAPI.DluznikFlotilaItem[] DluznikFlotilaItem;
        private String[] DluznikFlotilaItem_type_info = new String[]{'DluznikFlotilaItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikFlotilaItem'};
    }
    public class UzivatelKnzItem {
        public String ZISKATEL_KOD;
        public Integer ID_KNZ;
        public String EMAIL;
        public String OSOBNI_CISLO;
        public String DATUM_PLATNOSTI_OD;
        public String DATUM_PLATNOSTI_DO;
        private String[] ZISKATEL_KOD_type_info = new String[]{'ZISKATEL_KOD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_KNZ_type_info = new String[]{'ID_KNZ','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OSOBNI_CISLO_type_info = new String[]{'OSOBNI_CISLO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PLATNOSTI_OD_type_info = new String[]{'DATUM_PLATNOSTI_OD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PLATNOSTI_DO_type_info = new String[]{'DATUM_PLATNOSTI_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ZISKATEL_KOD','ID_KNZ','EMAIL','OSOBNI_CISLO','DATUM_PLATNOSTI_OD','DATUM_PLATNOSTI_DO'};
    }
    public class StavSmlouvyResponse_element {
        public KoopAPI.StavSmlouvyData StavSmlouvyResult;
        private String[] StavSmlouvyResult_type_info = new String[]{'StavSmlouvyResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'StavSmlouvyResult'};
    }
    public class DokumentItem {
        public KoopAPI.ArrayOfSouborItem SouborList;
        private String[] SouborList_type_info = new String[]{'SouborList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SouborList'};
    }
    public class ArrayOfInvesticeItem {
        public KoopAPI.InvesticeItem[] InvesticeItem;
        private String[] InvesticeItem_type_info = new String[]{'InvesticeItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'InvesticeItem'};
    }
    public class KmenTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class UzivatelKnzResponse_element {
        public KoopAPI.UzivatelKnzData UzivatelKnzResult;
        private String[] UzivatelKnzResult_type_info = new String[]{'UzivatelKnzResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UzivatelKnzResult'};
    }
    public class CekarnaStorenResponse_element {
        public KoopAPI.CekarnaStorenData CekarnaStorenResult;
        private String[] CekarnaStorenResult_type_info = new String[]{'CekarnaStorenResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CekarnaStorenResult'};
    }
    public class SmlouvaPNDAkceptace_element {
        public String IDpartner;
        public String kodZi;
        public String DatumOd;
        public Boolean list_x;
        public String IDdotazu;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] kodZi_type_info = new String[]{'kodZi','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumOd_type_info = new String[]{'DatumOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDdotazu_type_info = new String[]{'IDdotazu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','kodZi','DatumOd','list_x','IDdotazu'};
    }
    public class SmlouvyZaObdobiData {
        public KoopAPI.ArrayOfArrayOfString SmlouvyList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] SmlouvyList_type_info = new String[]{'SmlouvyList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SmlouvyList','StatusList','DataInfo','log'};
    }
    public class MistoPojisteniItem {
        public String CISLO_SMLOUVY;
        public String ID_PREDMET;
        public String NAZEV_OBJEKT;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_PREDMET_type_info = new String[]{'ID_PREDMET','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] NAZEV_OBJEKT_type_info = new String[]{'NAZEV_OBJEKT','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','ID_PREDMET','NAZEV_OBJEKT','ULICE','CISLO_DOMOVNI','PSC','OBEC'};
    }
    public class DluznikIndividualniItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String KOD_PRODUKTU;
        public String VERZE_PRODUKTU;
        public String STAV_SMLOUVY;
        public String ZPUSOB_PLATBY;
        public String MESICU_DLUH;
        public Decimal SPLATKA;
        public Decimal CASTECNA_UHRADA;
        public Decimal DLUH;
        public String RC_ICO;
        public String PRIJMENI;
        public String JMENO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String UPOMINKA_DATUM;
        public String UPOMINKA_INFO;
        public Decimal UPOMINKA_CASTKA;
        public String VYMAHANI_INFO;
        public Decimal ODPIS;
        public Decimal UPOMINACI_POPLATEK;
        public Decimal PREPLATEK;
        public String MAX_DATUM_SPLATNOSTI;
        public Decimal PROVIZE;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VERZE_PRODUKTU_type_info = new String[]{'VERZE_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MESICU_DLUH_type_info = new String[]{'MESICU_DLUH','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SPLATKA_type_info = new String[]{'SPLATKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] CASTECNA_UHRADA_type_info = new String[]{'CASTECNA_UHRADA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UPOMINKA_DATUM_type_info = new String[]{'UPOMINKA_DATUM','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UPOMINKA_INFO_type_info = new String[]{'UPOMINKA_INFO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UPOMINKA_CASTKA_type_info = new String[]{'UPOMINKA_CASTKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] VYMAHANI_INFO_type_info = new String[]{'VYMAHANI_INFO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ODPIS_type_info = new String[]{'ODPIS','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] UPOMINACI_POPLATEK_type_info = new String[]{'UPOMINACI_POPLATEK','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] PREPLATEK_type_info = new String[]{'PREPLATEK','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] MAX_DATUM_SPLATNOSTI_type_info = new String[]{'MAX_DATUM_SPLATNOSTI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PROVIZE_type_info = new String[]{'PROVIZE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','KOD_PRODUKTU','VERZE_PRODUKTU','STAV_SMLOUVY','ZPUSOB_PLATBY','MESICU_DLUH','SPLATKA','CASTECNA_UHRADA','DLUH','RC_ICO','PRIJMENI','JMENO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','UPOMINKA_DATUM','UPOMINKA_INFO','UPOMINKA_CASTKA','VYMAHANI_INFO','ODPIS','UPOMINACI_POPLATEK','PREPLATEK','MAX_DATUM_SPLATNOSTI','PROVIZE'};
    }
    public class Provize_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public Integer mesic;
        public Integer rok;
        public String hip;
        public String typ;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] mesic_type_info = new String[]{'mesic','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] rok_type_info = new String[]{'rok','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] hip_type_info = new String[]{'hip','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] typ_type_info = new String[]{'typ','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','mesic','rok','hip','typ','IDpartner','list_x'};
    }
    public class StavSmlouvyItem {
        public String CISLO_SMLOUVY;
        public String STAV_SMLOUVY;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','STAV_SMLOUVY'};
    }
    public class KmenResponse_element {
        public KoopAPI.KmenData KmenResult;
        private String[] KmenResult_type_info = new String[]{'KmenResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenResult'};
    }
    public class Dluznik_element {
        public Integer poDatuSplatnosti;
        public String jednotka;
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String datumPredpisuOd;
        public String IDpartner;
        public Boolean list_x;
        private String[] poDatuSplatnosti_type_info = new String[]{'poDatuSplatnosti','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] jednotka_type_info = new String[]{'jednotka','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] datumPredpisuOd_type_info = new String[]{'datumPredpisuOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'poDatuSplatnosti','jednotka','ziskatel','datumPredpisuOd','IDpartner','list_x'};
    }
    public class ArrayOfCiselnikFrekvencePlaceniItem {
        public KoopAPI.CiselnikFrekvencePlaceniItem[] CiselnikFrekvencePlaceniItem;
        private String[] CiselnikFrekvencePlaceniItem_type_info = new String[]{'CiselnikFrekvencePlaceniItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikFrekvencePlaceniItem'};
    }
    public class SmlouvaPNDCekarnaItem {
        public String CISLO_SMLOUVY;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public String DATUM_KONCE;
        public String DATUM_AKCEPTACE;
        public String KOD_PRODUKTU;
        public String PRIJMENI;
        public String JMENO;
        public String TELEFON;
        public String EMAIL;
        public String RC_ICO;
        public String STAV_SMLOUVY;
        public String POPIS_STAVU_SMLOUVY;
        public String ZISKATEL;
        public String SJEDNATEL;
        public String DATUM_PLATBY;
        public Decimal LHUTNI_POJISTNE;
        public Decimal CASTKA_PLATBY;
        public Integer ID_KNZ;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_KONCE_type_info = new String[]{'DATUM_KONCE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_AKCEPTACE_type_info = new String[]{'DATUM_AKCEPTACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_STAVU_SMLOUVY_type_info = new String[]{'POPIS_STAVU_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZISKATEL_type_info = new String[]{'ZISKATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PLATBY_type_info = new String[]{'DATUM_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] CASTKA_PLATBY_type_info = new String[]{'CASTKA_PLATBY','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ID_KNZ_type_info = new String[]{'ID_KNZ','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','DATUM_SJEDNANI','DATUM_POCATKU','DATUM_KONCE','DATUM_AKCEPTACE','KOD_PRODUKTU','PRIJMENI','JMENO','TELEFON','EMAIL','RC_ICO','STAV_SMLOUVY','POPIS_STAVU_SMLOUVY','ZISKATEL','SJEDNATEL','DATUM_PLATBY','LHUTNI_POJISTNE','CASTKA_PLATBY','ID_KNZ'};
    }
    public class CekarnaStorenData {
        public KoopAPI.CekarnaStorenTable_element CekarnaStorenTable;
        public KoopAPI.ArrayOfCekarnaStorenItem CekarnaStorenList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] CekarnaStorenTable_type_info = new String[]{'CekarnaStorenTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CekarnaStorenList_type_info = new String[]{'CekarnaStorenList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CekarnaStorenTable','CekarnaStorenList','StatusList','DataInfo','log'};
    }
    public class NovaSmlouvaTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class DluznikFlotila_element {
        public Integer mesicuPoSplatnosti;
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String IDpartner;
        public Boolean list_x;
        private String[] mesicuPoSplatnosti_type_info = new String[]{'mesicuPoSplatnosti','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'mesicuPoSplatnosti','ziskatel','IDpartner','list_x'};
    }
    public class ArrayOfSouborItem {
        public KoopAPI.SouborItem[] SouborItem;
        private String[] SouborItem_type_info = new String[]{'SouborItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SouborItem'};
    }
    public class DluznikIndividualniResponse_element {
        public KoopAPI.DluznikIndividualniData DluznikIndividualniResult;
        private String[] DluznikIndividualniResult_type_info = new String[]{'DluznikIndividualniResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'DluznikIndividualniResult'};
    }
    public class PNDNestalec_element {
        public String IDpartner;
        public Boolean list_x;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','list_x'};
    }
    public class NovinkyResponse_element {
        public KoopAPI.NovinkyData NovinkyResult;
        private String[] NovinkyResult_type_info = new String[]{'NovinkyResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovinkyResult'};
    }
    public class NovinkaItem {
        public KoopAPI.ArrayOfSouborItem SouborList;
        public DateTime PlatnostOd;
        public String Anotace;
        public String Sdeleni;
        private String[] SouborList_type_info = new String[]{'SouborList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PlatnostOd_type_info = new String[]{'PlatnostOd','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] Anotace_type_info = new String[]{'Anotace','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] Sdeleni_type_info = new String[]{'Sdeleni','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SouborList','PlatnostOd','Anotace','Sdeleni'};
    }
    public class InvesticeData {
        public KoopAPI.InvesticeTable_element InvesticeTable;
        public KoopAPI.ArrayOfInvesticeItem InvesticeList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        private String[] InvesticeTable_type_info = new String[]{'InvesticeTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] InvesticeList_type_info = new String[]{'InvesticeList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'InvesticeTable','InvesticeList','StatusList','DataInfo'};
    }
    public class UkonceneSmlouvyItem {
        public Integer UZAVERKA;
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String FLOTILA;
        public String KOD_PRODUKTU;
        public String RC_ICO;
        public String PRIJMENI;
        public String JMENO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String DATUM_UCINNOSTI_UKONCENI;
        public String DATUM_PROVEDENI_UKONCENI;
        public String NAZEV_UKONCENI;
        public String ZPUSOB_PLATBY;
        public Decimal ROCNI_POJISTNE;
        public Decimal LHUTNI_POJISTNE;
        public Decimal DLUH;
        public Boolean VINKULACE;
        private String[] UZAVERKA_type_info = new String[]{'UZAVERKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UCINNOSTI_UKONCENI_type_info = new String[]{'DATUM_UCINNOSTI_UKONCENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PROVEDENI_UKONCENI_type_info = new String[]{'DATUM_PROVEDENI_UKONCENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] NAZEV_UKONCENI_type_info = new String[]{'NAZEV_UKONCENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ROCNI_POJISTNE_type_info = new String[]{'ROCNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] VINKULACE_type_info = new String[]{'VINKULACE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UZAVERKA','CISLO_SMLOUVY','CISLO_NAVRHU','FLOTILA','KOD_PRODUKTU','RC_ICO','PRIJMENI','JMENO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','DATUM_UCINNOSTI_UKONCENI','DATUM_PROVEDENI_UKONCENI','NAZEV_UKONCENI','ZPUSOB_PLATBY','ROCNI_POJISTNE','LHUTNI_POJISTNE','DLUH','VINKULACE'};
    }
    public class VozidloItem {
        public String ID_VOZIDLO;
        public String RZ;
        public String VIN;
        public String ZNACKA;
        public String CISLO_TP;
        public String PALIVO;
        public String OBJEM_MOTOR;
        public String VYROBA;
        public String SEDADLA;
        public String HMOTNOST;
        public String VYKON_MOTOR;
        public String KATEGORIE;
        private String[] ID_VOZIDLO_type_info = new String[]{'ID_VOZIDLO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RZ_type_info = new String[]{'RZ','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VIN_type_info = new String[]{'VIN','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZNACKA_type_info = new String[]{'ZNACKA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_TP_type_info = new String[]{'CISLO_TP','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PALIVO_type_info = new String[]{'PALIVO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBJEM_MOTOR_type_info = new String[]{'OBJEM_MOTOR','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VYROBA_type_info = new String[]{'VYROBA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SEDADLA_type_info = new String[]{'SEDADLA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] HMOTNOST_type_info = new String[]{'HMOTNOST','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VYKON_MOTOR_type_info = new String[]{'VYKON_MOTOR','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KATEGORIE_type_info = new String[]{'KATEGORIE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ID_VOZIDLO','RZ','VIN','ZNACKA','CISLO_TP','PALIVO','OBJEM_MOTOR','VYROBA','SEDADLA','HMOTNOST','VYKON_MOTOR','KATEGORIE'};
    }
    public class CiselnikStavSmlouvyItem {
        public String STAV_SMLOUVY;
        public String POPIS;
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POPIS_type_info = new String[]{'POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'STAV_SMLOUVY','POPIS'};
    }
    public class ArrayOfUkonceneSmlouvyItem {
        public KoopAPI.UkonceneSmlouvyItem[] UkonceneSmlouvyItem;
        private String[] UkonceneSmlouvyItem_type_info = new String[]{'UkonceneSmlouvyItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'UkonceneSmlouvyItem'};
    }
    public class NovaSmlouvaRozsirena_element {
        public String IDpartner;
        public String kodZi;
        public String DatumOd;
        public Boolean list_x;
        public String IDdotazu;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] kodZi_type_info = new String[]{'kodZi','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumOd_type_info = new String[]{'DatumOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDdotazu_type_info = new String[]{'IDdotazu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','kodZi','DatumOd','list_x','IDdotazu'};
    }
    public class DokumentySmlouvy_element {
        public String IDpartner;
        public String kodZi;
        public String cisSml;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] kodZi_type_info = new String[]{'kodZi','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] cisSml_type_info = new String[]{'cisSml','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','kodZi','cisSml'};
    }
    public class DluznikIndividualni_element {
        public Integer mesicuPoSplatnosti;
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public String IDpartner;
        public Boolean list_x;
        private String[] mesicuPoSplatnosti_type_info = new String[]{'mesicuPoSplatnosti','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'mesicuPoSplatnosti','ziskatel','IDpartner','list_x'};
    }
    public class NovaSmlouvaVDPResponse_element {
        public KoopAPI.NovaSmlouvaDataVDP NovaSmlouvaVDPResult;
        private String[] NovaSmlouvaVDPResult_type_info = new String[]{'NovaSmlouvaVDPResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaVDPResult'};
    }
    public class ArrayOfCiselnikProduktItem {
        public KoopAPI.CiselnikProduktItem[] CiselnikProduktItem;
        private String[] CiselnikProduktItem_type_info = new String[]{'CiselnikProduktItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CiselnikProduktItem'};
    }
    public class KmenItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String FLOTILA;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public String DATUM_KONCE;
        public String DATUM_AKCEPTACE;
        public String KOD_PRODUKTU;
        public String VERZE_PRODUKTU;
        public String STAV_SMLOUVY;
        public String ZPUSOB_PLATBY;
        public String SJEDNATEL;
        public String PRIJMENI;
        public String JMENO;
        public String TELEFON;
        public String EMAIL;
        public String RC_ICO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String KOD_PROVIZE;
        public String DATUM_ZAPLACENO_DO;
        public Decimal KMENOVE_POJISTNE;
        public Decimal LHUTNI_POJISTNE;
        public Decimal SLEVA_PRI_PROC;
        public Decimal SLEVA_PRI_KC;
        public Integer DNY_DLUHU;
        public Decimal DLUH;
        public Integer FREKVENCE_PLACENI;
        public String KOD_STORNO;
        public String DATUM_PROVEDENI_STORNA;
        public String DATUM_UCINNOSTI_STORNA;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_KONCE_type_info = new String[]{'DATUM_KONCE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_AKCEPTACE_type_info = new String[]{'DATUM_AKCEPTACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VERZE_PRODUKTU_type_info = new String[]{'VERZE_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ZPUSOB_PLATBY_type_info = new String[]{'ZPUSOB_PLATBY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PROVIZE_type_info = new String[]{'KOD_PROVIZE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_ZAPLACENO_DO_type_info = new String[]{'DATUM_ZAPLACENO_DO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KMENOVE_POJISTNE_type_info = new String[]{'KMENOVE_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SLEVA_PRI_PROC_type_info = new String[]{'SLEVA_PRI_PROC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SLEVA_PRI_KC_type_info = new String[]{'SLEVA_PRI_KC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DNY_DLUHU_type_info = new String[]{'DNY_DLUHU','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DLUH_type_info = new String[]{'DLUH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] FREKVENCE_PLACENI_type_info = new String[]{'FREKVENCE_PLACENI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] KOD_STORNO_type_info = new String[]{'KOD_STORNO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PROVEDENI_STORNA_type_info = new String[]{'DATUM_PROVEDENI_STORNA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UCINNOSTI_STORNA_type_info = new String[]{'DATUM_UCINNOSTI_STORNA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','FLOTILA','DATUM_SJEDNANI','DATUM_POCATKU','DATUM_KONCE','DATUM_AKCEPTACE','KOD_PRODUKTU','VERZE_PRODUKTU','STAV_SMLOUVY','ZPUSOB_PLATBY','SJEDNATEL','PRIJMENI','JMENO','TELEFON','EMAIL','RC_ICO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','KOD_PROVIZE','DATUM_ZAPLACENO_DO','KMENOVE_POJISTNE','LHUTNI_POJISTNE','SLEVA_PRI_PROC','SLEVA_PRI_KC','DNY_DLUHU','DLUH','FREKVENCE_PLACENI','KOD_STORNO','DATUM_PROVEDENI_STORNA','DATUM_UCINNOSTI_STORNA'};
    }
    public class ExtraDataInfo {
        public String AktualizaceDat;
        public Integer PocetZaznamu;
        public String IDdotazu;
        private String[] AktualizaceDat_type_info = new String[]{'AktualizaceDat','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PocetZaznamu_type_info = new String[]{'PocetZaznamu','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDdotazu_type_info = new String[]{'IDdotazu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'AktualizaceDat','PocetZaznamu','IDdotazu'};
    }
    public class CekarnaStoren_element {
        public KoopAPI.ArrayOfZiskatel ziskatel;
        public Boolean vse;
        public String IDpartner;
        public Boolean list_x;
        private String[] ziskatel_type_info = new String[]{'ziskatel','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] vse_type_info = new String[]{'vse','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'ziskatel','vse','IDpartner','list_x'};
    }
    public class ArrayOfSmlouvaPNDAkceptaceItem {
        public KoopAPI.SmlouvaPNDAkceptaceItem[] SmlouvaPNDAkceptaceItem;
        private String[] SmlouvaPNDAkceptaceItem_type_info = new String[]{'SmlouvaPNDAkceptaceItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'SmlouvaPNDAkceptaceItem'};
    }
    public class NovaSmlouvaRozsirenaItem {
        public String CISLO_SMLOUVY;
        public String DATUM_SJEDNANI;
        public String DATUM_POCATKU;
        public String DATUM_KONCE;
        public String DATUM_AKCEPTACE;
        public String KOD_PRODUKTU;
        public String PREDCPS;
        public String PRIJMENI;
        public String JMENO;
        public String CELE_JMENO;
        public String TELEFON;
        public String MOBIL;
        public String EMAIL;
        public String RC_ICO;
        public String SJEDNATEL;
        public String STAV_SMLOUVY;
        public String DATUM_VLOZENI;
        public String FLOTILA;
        public String VIP_KLIENT;
        public String VIP_SMLOUVA;
        public String KOD_PROVIZE;
        public Decimal PROCENTO;
        public Decimal POJ_DOBA;
        public Decimal ROCNI;
        public Decimal PREDROCNI;
        public Decimal LHUTNI_POJISTNE;
        public Boolean VDP;
        public Boolean MPOS;
        public Integer FREKVENCE_PLACENI;
        public KoopAPI.ArrayOfDokumentItem DokumentList;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_SJEDNANI_type_info = new String[]{'DATUM_SJEDNANI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_POCATKU_type_info = new String[]{'DATUM_POCATKU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_KONCE_type_info = new String[]{'DATUM_KONCE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_AKCEPTACE_type_info = new String[]{'DATUM_AKCEPTACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PREDCPS_type_info = new String[]{'PREDCPS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CELE_JMENO_type_info = new String[]{'CELE_JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MOBIL_type_info = new String[]{'MOBIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] EMAIL_type_info = new String[]{'EMAIL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SJEDNATEL_type_info = new String[]{'SJEDNATEL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_VLOZENI_type_info = new String[]{'DATUM_VLOZENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VIP_KLIENT_type_info = new String[]{'VIP_KLIENT','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VIP_SMLOUVA_type_info = new String[]{'VIP_SMLOUVA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PROVIZE_type_info = new String[]{'KOD_PROVIZE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PROCENTO_type_info = new String[]{'PROCENTO','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] POJ_DOBA_type_info = new String[]{'POJ_DOBA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] ROCNI_type_info = new String[]{'ROCNI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] PREDROCNI_type_info = new String[]{'PREDROCNI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] LHUTNI_POJISTNE_type_info = new String[]{'LHUTNI_POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] VDP_type_info = new String[]{'VDP','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] MPOS_type_info = new String[]{'MPOS','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] FREKVENCE_PLACENI_type_info = new String[]{'FREKVENCE_PLACENI','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] DokumentList_type_info = new String[]{'DokumentList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','DATUM_SJEDNANI','DATUM_POCATKU','DATUM_KONCE','DATUM_AKCEPTACE','KOD_PRODUKTU','PREDCPS','PRIJMENI','JMENO','CELE_JMENO','TELEFON','MOBIL','EMAIL','RC_ICO','SJEDNATEL','STAV_SMLOUVY','DATUM_VLOZENI','FLOTILA','VIP_KLIENT','VIP_SMLOUVA','KOD_PROVIZE','PROCENTO','POJ_DOBA','ROCNI','PREDROCNI','LHUTNI_POJISTNE','VDP','MPOS','FREKVENCE_PLACENI','DokumentList','ULICE','CISLO_DOMOVNI','PSC','OBEC'};
    }
    public class NovinkyData {
        public KoopAPI.ArrayOfNovinkaItem NovinkaList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] NovinkaList_type_info = new String[]{'NovinkaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovinkaList','StatusList','DataInfo','log'};
    }
    public class SmlouvyZaObdobi_element {
        public String IDpartner;
        public String kodZi;
        public String DatumOd;
        public String DatumDo;
        public String IDdotazu;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] kodZi_type_info = new String[]{'kodZi','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumOd_type_info = new String[]{'DatumOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumDo_type_info = new String[]{'DatumDo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] IDdotazu_type_info = new String[]{'IDdotazu','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','kodZi','DatumOd','DatumDo','IDdotazu'};
    }
    public class NovaSmlouvaDataVDP {
        public KoopAPI.NovaSmlouvaTable_element NovaSmlouvaTable;
        public KoopAPI.ArrayOfNovaSmlouvaVDPItem NovaSmlouvaList;
        public KoopAPI.ArrayOfStatusDetail StatusList;
        public KoopAPI.ExtraDataInfo DataInfo;
        public KoopAPI.LogFile log;
        private String[] NovaSmlouvaTable_type_info = new String[]{'NovaSmlouvaTable','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] NovaSmlouvaList_type_info = new String[]{'NovaSmlouvaList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] StatusList_type_info = new String[]{'StatusList','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DataInfo_type_info = new String[]{'DataInfo','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] log_type_info = new String[]{'log','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'NovaSmlouvaTable','NovaSmlouvaList','StatusList','DataInfo','log'};
    }
    public class PojistneUdalostiItem {
        public String CISLO_SMLOUVY;
        public String CISLO_NAVRHU;
        public String FLOTILA;
        public String KOD_PRODUKTU;
        public String RC_ICO;
        public String PRIJMENI;
        public String JMENO;
        public String TITUL;
        public String ULICE;
        public String CISLO_DOMOVNI;
        public String PSC;
        public String OBEC;
        public String TELEFON;
        public String CISLO_UDALOSTI;
        public String SMLOUVA_OD;
        public String DATUM_VZNIK;
        public String DATUM_HLASENI;
        public String DATUM_PRIDELENI;
        public String DATUM_LIKVIDACE;
        public String DATUM_UZAVRENI;
        public String DRUH_PLNENI;
        public String DRUH_PLNENI_TEXT;
        public String STAV_SMLOUVY;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_NAVRHU_type_info = new String[]{'CISLO_NAVRHU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] FLOTILA_type_info = new String[]{'FLOTILA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] KOD_PRODUKTU_type_info = new String[]{'KOD_PRODUKTU','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] RC_ICO_type_info = new String[]{'RC_ICO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PRIJMENI_type_info = new String[]{'PRIJMENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] JMENO_type_info = new String[]{'JMENO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TITUL_type_info = new String[]{'TITUL','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ULICE_type_info = new String[]{'ULICE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_DOMOVNI_type_info = new String[]{'CISLO_DOMOVNI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] PSC_type_info = new String[]{'PSC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] OBEC_type_info = new String[]{'OBEC','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TELEFON_type_info = new String[]{'TELEFON','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CISLO_UDALOSTI_type_info = new String[]{'CISLO_UDALOSTI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] SMLOUVA_OD_type_info = new String[]{'SMLOUVA_OD','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_VZNIK_type_info = new String[]{'DATUM_VZNIK','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_HLASENI_type_info = new String[]{'DATUM_HLASENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_PRIDELENI_type_info = new String[]{'DATUM_PRIDELENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_LIKVIDACE_type_info = new String[]{'DATUM_LIKVIDACE','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UZAVRENI_type_info = new String[]{'DATUM_UZAVRENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DRUH_PLNENI_type_info = new String[]{'DRUH_PLNENI','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DRUH_PLNENI_TEXT_type_info = new String[]{'DRUH_PLNENI_TEXT','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_SMLOUVY_type_info = new String[]{'STAV_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','CISLO_NAVRHU','FLOTILA','KOD_PRODUKTU','RC_ICO','PRIJMENI','JMENO','TITUL','ULICE','CISLO_DOMOVNI','PSC','OBEC','TELEFON','CISLO_UDALOSTI','SMLOUVA_OD','DATUM_VZNIK','DATUM_HLASENI','DATUM_PRIDELENI','DATUM_LIKVIDACE','DATUM_UZAVRENI','DRUH_PLNENI','DRUH_PLNENI_TEXT','STAV_SMLOUVY'};
    }
    public class RizikoItem {
        public String CISLO_SMLOUVY;
        public Integer ID_RIZIKO;
        public String RIZIKO_POPIS;
        public String ID_VOZIDLO;
        public String ID_PREDMET;
        public String ID_OSOBA;
        public Decimal POJISTNA_CASTKA;
        public Decimal POJISTNE;
        public Decimal SU_CASTKA;
        public Decimal SU_PROC;
        public Decimal SU_MINIMUM;
        public Decimal SU_MAXIMUM;
        private String[] CISLO_SMLOUVY_type_info = new String[]{'CISLO_SMLOUVY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_RIZIKO_type_info = new String[]{'ID_RIZIKO','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] RIZIKO_POPIS_type_info = new String[]{'RIZIKO_POPIS','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_VOZIDLO_type_info = new String[]{'ID_VOZIDLO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_PREDMET_type_info = new String[]{'ID_PREDMET','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] ID_OSOBA_type_info = new String[]{'ID_OSOBA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POJISTNA_CASTKA_type_info = new String[]{'POJISTNA_CASTKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] POJISTNE_type_info = new String[]{'POJISTNE','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SU_CASTKA_type_info = new String[]{'SU_CASTKA','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SU_PROC_type_info = new String[]{'SU_PROC','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SU_MINIMUM_type_info = new String[]{'SU_MINIMUM','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] SU_MAXIMUM_type_info = new String[]{'SU_MAXIMUM','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_SMLOUVY','ID_RIZIKO','RIZIKO_POPIS','ID_VOZIDLO','ID_PREDMET','ID_OSOBA','POJISTNA_CASTKA','POJISTNE','SU_CASTKA','SU_PROC','SU_MINIMUM','SU_MAXIMUM'};
    }
    public class ArrayOfString {
        public String[] string_x;
        private String[] string_x_type_info = new String[]{'string','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'string_x'};
    }
    public class DluznikFlotilaItem {
        public String CISLO_FLOTILY;
        public String NAZEV_FLOTILY;
        public String STAV_FLOTILY;
        public String TYP_FLOTILY;
        public String MESICU_DLUH;
        public String DATUM_UCINNOSTI_STORNA;
        public String CELKOVY_POCET_SMLUV_FLOTILY;
        public String POCET_DLUZNYCH_SMLUV_FLOTILY;
        public Decimal DLUH_FLOTILY;
        public Decimal KUMULOVANY_DLUH_MH;
        public String UPOMINKA_DATUM;
        public String UPOMINKA_INFO;
        public String VYMAHANI_INFO;
        private String[] CISLO_FLOTILY_type_info = new String[]{'CISLO_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] NAZEV_FLOTILY_type_info = new String[]{'NAZEV_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] STAV_FLOTILY_type_info = new String[]{'STAV_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] TYP_FLOTILY_type_info = new String[]{'TYP_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] MESICU_DLUH_type_info = new String[]{'MESICU_DLUH','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DATUM_UCINNOSTI_STORNA_type_info = new String[]{'DATUM_UCINNOSTI_STORNA','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] CELKOVY_POCET_SMLUV_FLOTILY_type_info = new String[]{'CELKOVY_POCET_SMLUV_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] POCET_DLUZNYCH_SMLUV_FLOTILY_type_info = new String[]{'POCET_DLUZNYCH_SMLUV_FLOTILY','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DLUH_FLOTILY_type_info = new String[]{'DLUH_FLOTILY','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] KUMULOVANY_DLUH_MH_type_info = new String[]{'KUMULOVANY_DLUH_MH','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] UPOMINKA_DATUM_type_info = new String[]{'UPOMINKA_DATUM','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] UPOMINKA_INFO_type_info = new String[]{'UPOMINKA_INFO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] VYMAHANI_INFO_type_info = new String[]{'VYMAHANI_INFO','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'CISLO_FLOTILY','NAZEV_FLOTILY','STAV_FLOTILY','TYP_FLOTILY','MESICU_DLUH','DATUM_UCINNOSTI_STORNA','CELKOVY_POCET_SMLUV_FLOTILY','POCET_DLUZNYCH_SMLUV_FLOTILY','DLUH_FLOTILY','KUMULOVANY_DLUH_MH','UPOMINKA_DATUM','UPOMINKA_INFO','VYMAHANI_INFO'};
    }
    public class PNDNestalecTable_element {
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class InvesticeTip_element {
        public String IDpartner;
        public String DatumJednaniOd;
        public Boolean list_x;
        public String IDdotaz;
        private String[] IDpartner_type_info = new String[]{'IDpartner','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] DatumJednaniOd_type_info = new String[]{'DatumJednaniOd','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] list_x_type_info = new String[]{'list','https://extranet.koop.cz/',null,'1','1','false'};
        private String[] IDdotaz_type_info = new String[]{'IDdotaz','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'IDpartner','DatumJednaniOd','list_x','IDdotaz'};
    }
    public class ArrayOfKmenItem {
        public KoopAPI.KmenItem[] KmenItem;
        private String[] KmenItem_type_info = new String[]{'KmenItem','https://extranet.koop.cz/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'KmenItem'};
    }
    public class PojistneudalostiResponse_element {
        public KoopAPI.PojistneUdalostiData PojistneudalostiResult;
        private String[] PojistneudalostiResult_type_info = new String[]{'PojistneudalostiResult','https://extranet.koop.cz/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'https://extranet.koop.cz/','true','false'};
        private String[] field_order_type_info = new String[]{'PojistneudalostiResult'};
    }
    public class WSDataExtranetSoap {
        public String endpoint_x = 'https://wsextra.koop.cz/extranet/extranet.asmx';
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'https://extranet.koop.cz/', 'KoopAPI'};
        public KoopAPI.NeinkasniIntervenceData NeinkasniIntervence(String IDpartner,Integer DnyZpetne) {
            KoopAPI.NeinkasniIntervence_element request_x = new KoopAPI.NeinkasniIntervence_element();
            request_x.IDpartner = IDpartner;
            request_x.DnyZpetne = DnyZpetne;
            KoopAPI.NeinkasniIntervenceResponse_element response_x;
            Map<String, KoopAPI.NeinkasniIntervenceResponse_element> response_map_x = new Map<String, KoopAPI.NeinkasniIntervenceResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/NeinkasniIntervence',
              'https://extranet.koop.cz/',
              'NeinkasniIntervence',
              'https://extranet.koop.cz/',
              'NeinkasniIntervenceResponse',
              'KoopAPI.NeinkasniIntervenceResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.NeinkasniIntervenceResult;
        }
        public KoopAPI.DluznikFlotilaData DluznikFlotila(Integer mesicuPoSplatnosti,KoopAPI.ArrayOfZiskatel ziskatel,String IDpartner,Boolean list_x) {
            KoopAPI.DluznikFlotila_element request_x = new KoopAPI.DluznikFlotila_element();
            request_x.mesicuPoSplatnosti = mesicuPoSplatnosti;
            request_x.ziskatel = ziskatel;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.DluznikFlotilaResponse_element response_x;
            Map<String, KoopAPI.DluznikFlotilaResponse_element> response_map_x = new Map<String, KoopAPI.DluznikFlotilaResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/DluznikFlotila',
              'https://extranet.koop.cz/',
              'DluznikFlotila',
              'https://extranet.koop.cz/',
              'DluznikFlotilaResponse',
              'KoopAPI.DluznikFlotilaResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DluznikFlotilaResult;
        }
        public KoopAPI.DluznikData Dluznik(Integer poDatuSplatnosti,String jednotka,KoopAPI.ArrayOfZiskatel ziskatel,String datumPredpisuOd,String IDpartner,Boolean list_x) {
            KoopAPI.Dluznik_element request_x = new KoopAPI.Dluznik_element();
            request_x.poDatuSplatnosti = poDatuSplatnosti;
            request_x.jednotka = jednotka;
            request_x.ziskatel = ziskatel;
            request_x.datumPredpisuOd = datumPredpisuOd;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.DluznikResponse_element response_x;
            Map<String, KoopAPI.DluznikResponse_element> response_map_x = new Map<String, KoopAPI.DluznikResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Dluznik',
              'https://extranet.koop.cz/',
              'Dluznik',
              'https://extranet.koop.cz/',
              'DluznikResponse',
              'KoopAPI.DluznikResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DluznikResult;
        }
        public KoopAPI.NovaSmlouvaDataRozsirena NovaSmlouvaRozsirena(String IDpartner,String kodZi,String DatumOd,Boolean list_x,String IDdotazu) {
            KoopAPI.NovaSmlouvaRozsirena_element request_x = new KoopAPI.NovaSmlouvaRozsirena_element();
            request_x.IDpartner = IDpartner;
            request_x.kodZi = kodZi;
            request_x.DatumOd = DatumOd;
            request_x.list_x = list_x;
            request_x.IDdotazu = IDdotazu;
            KoopAPI.NovaSmlouvaRozsirenaResponse_element response_x;
            Map<String, KoopAPI.NovaSmlouvaRozsirenaResponse_element> response_map_x = new Map<String, KoopAPI.NovaSmlouvaRozsirenaResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/NovaSmlouvaRozsirena',
              'https://extranet.koop.cz/',
              'NovaSmlouvaRozsirena',
              'https://extranet.koop.cz/',
              'NovaSmlouvaRozsirenaResponse',
              'KoopAPI.NovaSmlouvaRozsirenaResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.NovaSmlouvaRozsirenaResult;
        }
        public KoopAPI.SmlouvaPNDDataAkceptace SmlouvaPNDAkceptace(String IDpartner,String kodZi,String DatumOd,Boolean list_x,String IDdotazu) {
            KoopAPI.SmlouvaPNDAkceptace_element request_x = new KoopAPI.SmlouvaPNDAkceptace_element();
            request_x.IDpartner = IDpartner;
            request_x.kodZi = kodZi;
            request_x.DatumOd = DatumOd;
            request_x.list_x = list_x;
            request_x.IDdotazu = IDdotazu;
            KoopAPI.SmlouvaPNDAkceptaceResponse_element response_x;
            Map<String, KoopAPI.SmlouvaPNDAkceptaceResponse_element> response_map_x = new Map<String, KoopAPI.SmlouvaPNDAkceptaceResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/SmlouvaPNDAkceptace',
              'https://extranet.koop.cz/',
              'SmlouvaPNDAkceptace',
              'https://extranet.koop.cz/',
              'SmlouvaPNDAkceptaceResponse',
              'KoopAPI.SmlouvaPNDAkceptaceResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.SmlouvaPNDAkceptaceResult;
        }
        public KoopAPI.UzivatelKnzData UzivatelKnz(KoopAPI.ArrayOfZiskatel ziskatel,String IDpartner,Boolean vse,Boolean list_x) {
            KoopAPI.UzivatelKnz_element request_x = new KoopAPI.UzivatelKnz_element();
            request_x.ziskatel = ziskatel;
            request_x.IDpartner = IDpartner;
            request_x.vse = vse;
            request_x.list_x = list_x;
            KoopAPI.UzivatelKnzResponse_element response_x;
            Map<String, KoopAPI.UzivatelKnzResponse_element> response_map_x = new Map<String, KoopAPI.UzivatelKnzResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/UzivatelKnz',
              'https://extranet.koop.cz/',
              'UzivatelKnz',
              'https://extranet.koop.cz/',
              'UzivatelKnzResponse',
              'KoopAPI.UzivatelKnzResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.UzivatelKnzResult;
        }
        public KoopAPI.StavSmlouvyData StavSmlouvy(KoopAPI.ArrayOfZiskatel ziskatel,String cisloSmlouvy,String IDpartner,Boolean list_x) {
            KoopAPI.StavSmlouvy_element request_x = new KoopAPI.StavSmlouvy_element();
            request_x.ziskatel = ziskatel;
            request_x.cisloSmlouvy = cisloSmlouvy;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.StavSmlouvyResponse_element response_x;
            Map<String, KoopAPI.StavSmlouvyResponse_element> response_map_x = new Map<String, KoopAPI.StavSmlouvyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/StavSmlouvy',
              'https://extranet.koop.cz/',
              'StavSmlouvy',
              'https://extranet.koop.cz/',
              'StavSmlouvyResponse',
              'KoopAPI.StavSmlouvyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.StavSmlouvyResult;
        }
        public KoopAPI.InvesticeData InvesticeTip(String IDpartner,String DatumJednaniOd,Boolean list_x,String IDdotaz) {
            KoopAPI.InvesticeTip_element request_x = new KoopAPI.InvesticeTip_element();
            request_x.IDpartner = IDpartner;
            request_x.DatumJednaniOd = DatumJednaniOd;
            request_x.list_x = list_x;
            request_x.IDdotaz = IDdotaz;
            KoopAPI.InvesticeTipResponse_element response_x;
            Map<String, KoopAPI.InvesticeTipResponse_element> response_map_x = new Map<String, KoopAPI.InvesticeTipResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/InvesticeTip',
              'https://extranet.koop.cz/',
              'InvesticeTip',
              'https://extranet.koop.cz/',
              'InvesticeTipResponse',
              'KoopAPI.InvesticeTipResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.InvesticeTipResult;
        }
        public KoopAPI.DluznikIndividualniData DluznikIndividualni(Integer mesicuPoSplatnosti,KoopAPI.ArrayOfZiskatel ziskatel,String IDpartner,Boolean list_x) {
            KoopAPI.DluznikIndividualni_element request_x = new KoopAPI.DluznikIndividualni_element();
            request_x.mesicuPoSplatnosti = mesicuPoSplatnosti;
            request_x.ziskatel = ziskatel;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.DluznikIndividualniResponse_element response_x;
            Map<String, KoopAPI.DluznikIndividualniResponse_element> response_map_x = new Map<String, KoopAPI.DluznikIndividualniResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/DluznikIndividualni',
              'https://extranet.koop.cz/',
              'DluznikIndividualni',
              'https://extranet.koop.cz/',
              'DluznikIndividualniResponse',
              'KoopAPI.DluznikIndividualniResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DluznikIndividualniResult;
        }
        public KoopAPI.NovinkyData Novinky(String IDpartner) {
            KoopAPI.Novinky_element request_x = new KoopAPI.Novinky_element();
            request_x.IDpartner = IDpartner;
            KoopAPI.NovinkyResponse_element response_x;
            Map<String, KoopAPI.NovinkyResponse_element> response_map_x = new Map<String, KoopAPI.NovinkyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Novinky',
              'https://extranet.koop.cz/',
              'Novinky',
              'https://extranet.koop.cz/',
              'NovinkyResponse',
              'KoopAPI.NovinkyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.NovinkyResult;
        }
        public KoopAPI.KmenData Kmen(KoopAPI.ArrayOfZiskatel ziskatel,String stavSmlouvy,String IDpartner,Boolean list_x) {
            KoopAPI.Kmen_element request_x = new KoopAPI.Kmen_element();
            request_x.ziskatel = ziskatel;
            request_x.stavSmlouvy = stavSmlouvy;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.KmenResponse_element response_x;
            Map<String, KoopAPI.KmenResponse_element> response_map_x = new Map<String, KoopAPI.KmenResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Kmen',
              'https://extranet.koop.cz/',
              'Kmen',
              'https://extranet.koop.cz/',
              'KmenResponse',
              'KoopAPI.KmenResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.KmenResult;
        }
        public KoopAPI.DocumentsData DokumentySmlouvy(String IDpartner,String kodZi,String cisSml) {
            KoopAPI.DokumentySmlouvy_element request_x = new KoopAPI.DokumentySmlouvy_element();
            request_x.IDpartner = IDpartner;
            request_x.kodZi = kodZi;
            request_x.cisSml = cisSml;
            KoopAPI.DokumentySmlouvyResponse_element response_x;
            Map<String, KoopAPI.DokumentySmlouvyResponse_element> response_map_x = new Map<String, KoopAPI.DokumentySmlouvyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/DokumentySmlouvy',
              'https://extranet.koop.cz/',
              'DokumentySmlouvy',
              'https://extranet.koop.cz/',
              'DokumentySmlouvyResponse',
              'KoopAPI.DokumentySmlouvyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DokumentySmlouvyResult;
        }
        public KoopAPI.UkonceneSmlouvyData Ukoncene(KoopAPI.ArrayOfZiskatel ziskatel,Integer mesic,Integer rok,String typ,String IDpartner,Boolean list_x) {
            KoopAPI.Ukoncene_element request_x = new KoopAPI.Ukoncene_element();
            request_x.ziskatel = ziskatel;
            request_x.mesic = mesic;
            request_x.rok = rok;
            request_x.typ = typ;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.UkonceneResponse_element response_x;
            Map<String, KoopAPI.UkonceneResponse_element> response_map_x = new Map<String, KoopAPI.UkonceneResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Ukoncene',
              'https://extranet.koop.cz/',
              'Ukoncene',
              'https://extranet.koop.cz/',
              'UkonceneResponse',
              'KoopAPI.UkonceneResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.UkonceneResult;
        }
        public KoopAPI.CiselnikyData Ciselniky(String IDpartner) {
            KoopAPI.Ciselniky_element request_x = new KoopAPI.Ciselniky_element();
            request_x.IDpartner = IDpartner;
            KoopAPI.CiselnikyResponse_element response_x;
            Map<String, KoopAPI.CiselnikyResponse_element> response_map_x = new Map<String, KoopAPI.CiselnikyResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Ciselniky',
              'https://extranet.koop.cz/',
              'Ciselniky',
              'https://extranet.koop.cz/',
              'CiselnikyResponse',
              'KoopAPI.CiselnikyResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CiselnikyResult;
        }
        public KoopAPI.NovaSmlouvaDataVDP NovaSmlouvaVDP(String IDpartner,String kodZi,String DatumOd,Boolean list_x,String IDdotazu) {
            KoopAPI.NovaSmlouvaVDP_element request_x = new KoopAPI.NovaSmlouvaVDP_element();
            request_x.IDpartner = IDpartner;
            request_x.kodZi = kodZi;
            request_x.DatumOd = DatumOd;
            request_x.list_x = list_x;
            request_x.IDdotazu = IDdotazu;
            KoopAPI.NovaSmlouvaVDPResponse_element response_x;
            Map<String, KoopAPI.NovaSmlouvaVDPResponse_element> response_map_x = new Map<String, KoopAPI.NovaSmlouvaVDPResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/NovaSmlouvaVDP',
              'https://extranet.koop.cz/',
              'NovaSmlouvaVDP',
              'https://extranet.koop.cz/',
              'NovaSmlouvaVDPResponse',
              'KoopAPI.NovaSmlouvaVDPResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.NovaSmlouvaVDPResult;
        }
        public KoopAPI.SmlouvaPNDCekarnaData PNDCekarna(KoopAPI.ArrayOfZiskatel ziskatel,String stavSmlouvy,String cisloSmlouvy,String IDpartner,Boolean list_x) {
            KoopAPI.PNDCekarna_element request_x = new KoopAPI.PNDCekarna_element();
            request_x.ziskatel = ziskatel;
            request_x.stavSmlouvy = stavSmlouvy;
            request_x.cisloSmlouvy = cisloSmlouvy;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.PNDCekarnaResponse_element response_x;
            Map<String, KoopAPI.PNDCekarnaResponse_element> response_map_x = new Map<String, KoopAPI.PNDCekarnaResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/PNDCekarna',
              'https://extranet.koop.cz/',
              'PNDCekarna',
              'https://extranet.koop.cz/',
              'PNDCekarnaResponse',
              'KoopAPI.PNDCekarnaResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.PNDCekarnaResult;
        }
        public KoopAPI.CekarnaStorenData CekarnaStoren(KoopAPI.ArrayOfZiskatel ziskatel,Boolean vse,String IDpartner,Boolean list_x) {
            KoopAPI.CekarnaStoren_element request_x = new KoopAPI.CekarnaStoren_element();
            request_x.ziskatel = ziskatel;
            request_x.vse = vse;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.CekarnaStorenResponse_element response_x;
            Map<String, KoopAPI.CekarnaStorenResponse_element> response_map_x = new Map<String, KoopAPI.CekarnaStorenResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/CekarnaStoren',
              'https://extranet.koop.cz/',
              'CekarnaStoren',
              'https://extranet.koop.cz/',
              'CekarnaStorenResponse',
              'KoopAPI.CekarnaStorenResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CekarnaStorenResult;
        }
        public KoopAPI.PNDNestalecData PNDNestalec(String IDpartner,Boolean list_x) {
            KoopAPI.PNDNestalec_element request_x = new KoopAPI.PNDNestalec_element();
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.PNDNestalecResponse_element response_x;
            Map<String, KoopAPI.PNDNestalecResponse_element> response_map_x = new Map<String, KoopAPI.PNDNestalecResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/PNDNestalec',
              'https://extranet.koop.cz/',
              'PNDNestalec',
              'https://extranet.koop.cz/',
              'PNDNestalecResponse',
              'KoopAPI.PNDNestalecResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.PNDNestalecResult;
        }
        public KoopAPI.PojistneUdalostiData Pojistneudalosti(KoopAPI.ArrayOfZiskatel ziskatel,String datumVznikOd,String datumHlaseniOd,String cisloSmlouvy,String cisloNavrhu,String cisloUdalosti,String IDpartner,Boolean list_x) {
            KoopAPI.Pojistneudalosti_element request_x = new KoopAPI.Pojistneudalosti_element();
            request_x.ziskatel = ziskatel;
            request_x.datumVznikOd = datumVznikOd;
            request_x.datumHlaseniOd = datumHlaseniOd;
            request_x.cisloSmlouvy = cisloSmlouvy;
            request_x.cisloNavrhu = cisloNavrhu;
            request_x.cisloUdalosti = cisloUdalosti;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.PojistneudalostiResponse_element response_x;
            Map<String, KoopAPI.PojistneudalostiResponse_element> response_map_x = new Map<String, KoopAPI.PojistneudalostiResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Pojistneudalosti',
              'https://extranet.koop.cz/',
              'Pojistneudalosti',
              'https://extranet.koop.cz/',
              'PojistneudalostiResponse',
              'KoopAPI.PojistneudalostiResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.PojistneudalostiResult;
        }
        public KoopAPI.ProvizeData Provize(KoopAPI.ArrayOfZiskatel ziskatel,Integer mesic,Integer rok,String hip,String typ,String IDpartner,Boolean list_x) {
            KoopAPI.Provize_element request_x = new KoopAPI.Provize_element();
            request_x.ziskatel = ziskatel;
            request_x.mesic = mesic;
            request_x.rok = rok;
            request_x.hip = hip;
            request_x.typ = typ;
            request_x.IDpartner = IDpartner;
            request_x.list_x = list_x;
            KoopAPI.ProvizeResponse_element response_x;
            Map<String, KoopAPI.ProvizeResponse_element> response_map_x = new Map<String, KoopAPI.ProvizeResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/Provize',
              'https://extranet.koop.cz/',
              'Provize',
              'https://extranet.koop.cz/',
              'ProvizeResponse',
              'KoopAPI.ProvizeResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.ProvizeResult;
        }
        public KoopAPI.SmlouvyZaObdobiData SmlouvyZaObdobi(String IDpartner,String kodZi,String DatumOd,String DatumDo,String IDdotazu) {
            KoopAPI.SmlouvyZaObdobi_element request_x = new KoopAPI.SmlouvyZaObdobi_element();
            request_x.IDpartner = IDpartner;
            request_x.kodZi = kodZi;
            request_x.DatumOd = DatumOd;
            request_x.DatumDo = DatumDo;
            request_x.IDdotazu = IDdotazu;
            KoopAPI.SmlouvyZaObdobiResponse_element response_x;
            Map<String, KoopAPI.SmlouvyZaObdobiResponse_element> response_map_x = new Map<String, KoopAPI.SmlouvyZaObdobiResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/SmlouvyZaObdobi',
              'https://extranet.koop.cz/',
              'SmlouvyZaObdobi',
              'https://extranet.koop.cz/',
              'SmlouvyZaObdobiResponse',
              'KoopAPI.SmlouvyZaObdobiResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.SmlouvyZaObdobiResult;
        }
        public KoopAPI.KmenDetailData KmenDetail(KoopAPI.ArrayOfZiskatel ziskatel,String cisloSmlouvy,String IDpartner) {
            KoopAPI.KmenDetail_element request_x = new KoopAPI.KmenDetail_element();
            request_x.ziskatel = ziskatel;
            request_x.cisloSmlouvy = cisloSmlouvy;
            request_x.IDpartner = IDpartner;
            KoopAPI.KmenDetailResponse_element response_x;
            Map<String, KoopAPI.KmenDetailResponse_element> response_map_x = new Map<String, KoopAPI.KmenDetailResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'https://extranet.koop.cz/KmenDetail',
              'https://extranet.koop.cz/',
              'KmenDetail',
              'https://extranet.koop.cz/',
              'KmenDetailResponse',
              'KoopAPI.KmenDetailResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.KmenDetailResult;
        }
    }
}